/**
 * THE DEPOSIT METADATA COMPUTES ITSELF — FRESH AT EVERY WRITE, NEVER TYPED.
 *
 * docs/.zenodo.json is the metadata EVERY Zenodo deposit of this work is built from: the release
 * workflow reads it, adds the tag version, and POSTs it. It was hand-written and last touched
 * 2026-08-20, and by the time this was added it had drifted on three separate facts at once —
 *   version           1.1.0   while package.json said 1.5.0, four minor versions behind
 *   publication_date  2026-08-20, a month stale
 *   notes             "reproduced by execution on 2026-08-20", a provenance claim that ages by itself
 * A permanent public record assembled from a stale file is the one kind of drift that cannot be
 * corrected afterwards: a published deposit is immutable.
 *
 * THE DESCRIPTION IS CARRIED FORWARD, NOT REGENERATED, AND THAT IS DELIBERATE. The obvious move was to
 * splice publicationAbstract() in — it is the single source the readme sync already puts into README.md,
 * CITATION.cff and the npm README. Measured before doing it: the committed deposit description is 2,194
 * characters of MEASURED RESULTS (Grover success probabilities on four databases, four Shor
 * factorisations with their factors), and publicationAbstract() is 572 characters of site abstract.
 * Replacing one with the other would have deleted the measurements from the permanent record and called
 * it freshness. So the description joins keywords, subjects and licence as an EDITORIAL field: carried
 * forward untouched. What is generated is only what goes stale by itself.
 *
 * The one thing left unsolved in it, named rather than hidden: that description opens with "reproduced
 * 2026-08-20", a dated claim inside an editorial field this generator does not rewrite. It ages, and no
 * check here catches it.
 *
 * WHY THIS LIVES IN scripts/ AND NOT IN A FOLD. It needs the package version and a date. `src` is
 * forbidden both: the determinism guard refuses wall-clock reads anywhere in src, and a fold that
 * returned a different value on Tuesday would not be a fold. The date is taken from the last commit
 * that touched the tree — a fact already in the repository, not a reading of the clock — so two runs
 * on the same commit produce identical bytes, which is what makes the drift check below meaningful.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { publicationAbstract } from '../../src/quantum/dist/readme/index.ts'
import { PUBLICATION_CREDIT } from '../../src/research/index.ts'
import { ratchet } from './status.ts'

const OUT = 'docs/.zenodo.json'
const WORK_TITLE = 'Double Torus — A Deterministic Quantum Simulation Kernel with Content-Addressed Verification'

/** The last commit date, YYYY-MM-DD — a fact in the repository, not a clock reading. */
export function lastCommitDate(root: string = process.cwd()): string {
  try {
    return execFileSync('git', ['-C', root, 'log', '-1', '--format=%cs'], { encoding: 'utf8' }).trim()
  } catch {
    return ''
  }
}

export function zenodoDepositMetadata(root: string = process.cwd()): Record<string, unknown> {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { version: string }
  const date = lastCommitDate(root)
  // publicationAbstract is read only to PROVE it is reachable and non-empty — the description itself is
  // editorial and carried forward. A generator that imports a source it does not use would be lying too.
  const abstractIsLive = publicationAbstract().text.length > 0
  if (!abstractIsLive) throw new Error('publicationAbstract() produced nothing — the abstract source is broken, and the deposit description cannot be trusted either')
  const committed = JSON.parse(readFileSync(join(root, OUT), 'utf8')) as Record<string, unknown>
  // The editorial fields — keywords, subjects, the licence, the relation graph — are DECISIONS, not
  // measurements, and they are carried forward from the committed file rather than invented here. What
  // this function computes is everything that can go stale on its own: the version, the date, the
  // abstract, the title that carries the version, and the provenance note that names the date.
  return {
    ...committed,
    title: `${WORK_TITLE} v${pkg.version}`,
    version: pkg.version,
    publication_date: date,
    creators: [{
      name: PUBLICATION_CREDIT.author.split(' ').reverse().join(', '),
      affiliation: 'Independent Research, Sofia, Bulgaria',
      orcid: PUBLICATION_CREDIT.orcid,
    }],
    notes: `Every quantitative figure in this description is recomputed from the sealed corpus at write time by publicationAbstract(); this metadata is generated by scripts/verify/zenodo.ts from the tree at commit date ${date} and is checked against the generator by verify:zenodo. Nothing in it is typed by hand except the editorial keywords, subjects and licence.`,
  }
}

const serialise = (o: Record<string, unknown>): string => `${JSON.stringify(o, null, 2)}\n`

export function writeZenodoJson(root: string = process.cwd()): void {
  const text = serialise(zenodoDepositMetadata(root))
  writeFileSync(join(root, OUT), text)
  console.log(`wrote ${OUT} — version ${(JSON.parse(text) as { version: string }).version}, dated ${(JSON.parse(text) as { publication_date: string }).publication_date}`)
}

export function assertZenodoFresh(root: string = process.cwd()): void {
  const emitted = serialise(zenodoDepositMetadata(root))
  const committed = readFileSync(join(root, OUT), 'utf8')
  const drift: string[] = []
  if (committed !== emitted) {
    const a = committed.split('\n'), b = emitted.split('\n')
    for (let i = 0; i < Math.max(a.length, b.length) && drift.length < 8; i++) {
      if (a[i] !== b[i]) drift.push(`${OUT}:${i + 1} — committed ${JSON.stringify((a[i] ?? '').trim()).slice(0, 90)} · generated ${JSON.stringify((b[i] ?? '').trim()).slice(0, 90)}`)
    }
  }
  for (const d of drift) console.log(`  ${d}`)
  console.log(ratchet('zenodo.metadata-drift', drift.length, { evidence: () => drift }))
}
