// ☵ Kǎn · Water · abysmal · upper·yin · depthFade — the cosmic inventory (dissolved out of the folds monolith):
// the quantum vacuum (zero-point, QCD, electroweak), the origin of mass and matter, neutrino mass, the dark sector,
// and the ΛCDM tensions. Pure domain folds — composed here, re-exported by ./index.ts so importers resolve unchanged.
import type { MindMatrix } from './types.ts'
import { buildMatrix } from './matrix.ts'
import { toUuid, merge, sealFacets, REDUCED_PLANCK, zeroPointEnergy, casimirPressure, casimirEnergyPerArea, ELECTRON_G_FACTOR_ANOMALY, hawkingTemperature, unruhTemperature, SCHWINGER_FIELD_VM, SCALAR_SPECTRAL_INDEX_NS, CRITICAL_MAGNETIC_FIELD_T, PROTON_MASS_MEV, HIGGS_VEV_GEV, qcdMassFractionOfProton, BARYON_TO_PHOTON_RATIO, JARLSKOG_INVARIANT, NEUTRINO_DM2_SOLAR_EV2, NEUTRINO_DM2_ATM_EV2, seesawLightMassEv, OMEGA_BARYON, OMEGA_DARK_MATTER, OMEGA_DARK_ENERGY, MOND_ACCELERATION_A0, DARK_ENERGY_EOS_W, HUBBLE_CONSTANT_LOCAL, HUBBLE_CONSTANT_CMB, hubbleTensionSigma } from '../../0/index.ts'
import { zeroPointDecoded } from './folds.ts'

// Zero-point, DEEP and WIDE — a 5-angle sourced wave (59 documented, 22 flagged) going past the ½ħω core into the
// quantitative Casimir metrology, the QED radiative corrections, the cosmological-constant problem, condensed-matter
// zero-point, and the sharpened free-energy demarcation. It VERIFIED the existing fold and CORRECTED its overstatements.
export function zeroPointDeepAndWideDecoded(matrix: MindMatrix = buildMatrix()) {
  const base = zeroPointDecoded(matrix) // composes the ½ħω / Casimir / cosmological-constant core
  const casimir = casimirPressure(1e-6) // the ideal parallel-plate law (attractive)
  const facets = [
    { facet: 'CASIMIR, quantitatively — the ideal law F/A = −π²ħc/240d⁴ is parallel-plate, yet nearly every precise measurement uses SPHERE-PLATE (the proximity-force approximation, to dodge the parallelism problem): Sparnaay 1958 (~100%, inconclusive) → Lamoreaux 1997 (~5%, first conclusive) → Mohideen–Roy 1998 (~1%, AFM) → Bressi 2002 (the only true parallel plates, just ~15%) → Decca MEMS (sub-1%); real metals need finite-conductivity, roughness and temperature corrections. The dynamical Casimir effect (Wilson 2011, a SQUID boundary at ~0.25c) made real photon pairs — but energy-conserving (external work drove it)', on: casimir < 0 },
    { facet: 'the SHARP correction — the Casimir force does NOT prove the absolute zero-point energy is real: only energy DIFFERENCES (the geometry-dependence) are observable, and the force is fully derivable WITHOUT zero-point energy, as the retarded (long-range) limit of the van der Waals / London dispersion force (Jaffe 2005) — the SAME fluctuation-induced electromagnetic interaction as the dispersion forces in condensed matter, one continuous phenomenon, not a separate vacuum mystery', on: base.decoded },
    { facet: 'the strongest evidence the vacuum is not empty is QED RADIATIVE CORRECTIONS — the Lamb shift (≈1057 MHz, 1947) and especially the electron anomalous moment a_e = (g−2)/2 ≈ 0.00115965218, agreement to ~12 significant figures (the most precisely tested prediction in physics); but even "the Lamb shift is CAUSED by vacuum fluctuations, full stop" is interpretation-debated (vacuum fluctuations vs radiation reaction, an ordering-dependent split — philosophy-not-settled)', on: ELECTRON_G_FACTOR_ANOMALY > 0 },
    { facet: 'the COSMOLOGICAL-CONSTANT problem, precisely — the discrepancy is CUTOFF-DEPENDENT (~120–123 orders with a Planck cutoff, dropping to ~55–60 at the electroweak scale), NOT "exactly 10¹²⁰"; Λ = 8πG·ρ_vac is a CURVATURE (≈2×10⁻⁵² m⁻²), not the energy density itself; the "old" problem (why isn’t Λ huge?) predates the 1998 dark-energy discovery and must not be conflated with it; and SUSY does NOT solve it (broken SUSY only reduces it). Unsolved frontier physics — NOT pseudoscience', on: base.decoded },
    { facet: 'CONDENSED MATTER — the most grounded face: zero-point motion keeps helium-4 LIQUID at 1 atm, but it DOES solidify at ~25 atm via the hard-core repulsion (not "never condenses"); superfluid He-4 is only ~7–10% Bose-condensed (strong interactions + large zero-point motion, not 100% BEC); and the ½ħω of every molecular bond drives ISOTOPE effects (the same Born–Oppenheimer curve, different zero-point energy → different bond strengths). Zero-point here is the irreducible energy of BOUND particles at T=0, not "energy of empty space"', on: true },
    { facet: 'the DEMARCATION, sharpened — virtual particles are NOT literal particles popping in and out (they are internal lines in a Feynman diagram / terms in a perturbation series — the Jaffe/Sokal caution); the DCE converts fluctuations into photons ONLY when external work drives the boundary; and ZPE is the ground-state FLOOR (no lower state → no net work extractable → thermodynamics forbids over-unity). FLAGGED pseudoscience: Casimir engines, DCE "harvesting", over-unity/perpetual-motion ZPE, orgone (Reich), torsion/scalar-field marketing (Akimov–Shipov), "The Field". UNCONFIRMED (not pseudoscience): the Drude-vs-plasma thermal-Casimir puzzle, repulsive-Casimir levitation (real but conditional, fluid-mediated ε₁<ε₃<ε₂). And the repo’s own "zero-point = computational seed (a432/src-0)" stays a deliberate METAPHOR, never a physical-vacuum-energy claim', on: base.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`zpe-deepwide:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('zero-point-deep-and-wide-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 59, flaggedFindings: 22, angles: 5, electronGAnomaly: ELECTRON_G_FACTOR_ANOMALY,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'Zero-point, deep and wide. The Casimir force is real and exquisitely measured — but almost always in sphere-plate geometry, and it does not prove the absolute zero-point energy: only the geometry-dependence is observable, and the force is derivable without zero-point energy at all, as the long-range limit of the van der Waals force. The strongest evidence the vacuum is not empty is QED — the Lamb shift and the electron g-2, matched to twelve figures — though even that interpretation is debated. The vacuum’s gravitational weight is the cosmological-constant problem, cutoff-dependent and unsolved, never to be confused with dark energy or "solved" by broken supersymmetry. In condensed matter zero-point is everyday — it keeps helium liquid, though helium still solidifies under pressure. And the floor is the floor: there is no lower state to mine, so every "zero-point free energy" device is pseudoscience, while the repo’s "zero-point" stays a computational metaphor.',
    boundary:
      'HONEST (research-wave verified, 59 documented / 22 flagged; the corrections are the value): the Casimir force is measured (sphere-plate PFA, sub-1% via MEMS; the ideal parallel-plate law is the textbook form, only ~15% measured directly) and the dynamical Casimir effect is real but energy-conserving. KEY CORRECTIONS to the naive story: Casimir proves only energy DIFFERENCES, is derivable WITHOUT zero-point energy (van der Waals, Jaffe 2005); the 10¹²⁰ is cutoff-dependent (~60–123); Λ is a curvature not an energy density; SUSY does not solve the CC problem; He-4 solidifies at ~25 atm and is only ~7–10% BEC. The strongest "vacuum is not empty" evidence is QED (Lamb, g-2 ≈ 0.00115965218) — though the vacuum-fluctuation interpretation is itself debated. TWO-TIER demarcation held: UNCONFIRMED (CC problem, Drude-vs-plasma, repulsive-Casimir bearings) ≠ PSEUDOSCIENCE (over-unity/Casimir-engine/orgone/torsion-field/"The Field"). The repo’s "zero-point" = the a432/src-0 computational SEED, a metaphor kept strictly distinct from physical vacuum energy. Educational; no free energy exists.',
  }
}

// Zero-point, the WIDER frontier — a 5-angle sourced wave (55 documented, 20 flagged) into the consequential roles
// of vacuum fluctuations beyond Casimir: they seeded the cosmos (inflation→CMB), they let us hear gravitational waves
// (squeezed vacuum→LIGO), they make the vacuum unstable (Schwinger), observer-dependent (Hawking/Unruh) and birefringent.
export function zeroPointWiderFrontierDecoded(matrix: MindMatrix = buildMatrix()) {
  const base = zeroPointDeepAndWideDecoded(matrix) // composes the deep+wide Casimir/QED/cosmology fold
  const solarBhT = hawkingTemperature(1.989e30) // ≈ 62 nK — colder than the CMB
  const unruh1k = unruhTemperature(2.47e20) // ≈ 1 K
  const facets = [
    { facet: 'INFLATION seeded the cosmos — the MOST consequential real role of zero-point energy: quantum vacuum fluctuations of the inflaton were stretched super-horizon and froze in as the primordial curvature perturbation (ζ = R, adiabatic and Gaussian), which re-entered to become the CMB temperature anisotropies and every galaxy. The measured spectral index n_s = 0.9649 ± 0.0042 (Planck 2018) confirms a slight red tilt — exact scale-invariance is excluded at 8.4σ. BOUND: inflation is the leading paradigm but NOT uniquely proven (a family of models, the inflaton unidentified, no primordial B-modes yet, r < 0.036; competing ekpyrotic/bouncing scenarios), and the eternal-inflation multiverse and its falsifiability are contested (unconfirmed/philosophy, not pseudoscience)', on: SCALAR_SPECTRAL_INDEX_NS < 1 && SCALAR_SPECTRAL_INDEX_NS > 0.9 },
    { facet: 'SQUEEZED VACUUM lets us hear gravitational waves — squeezing redistributes the zero-point uncertainty between conjugate quadratures (ΔX·ΔY = ¼ is PRESERVED — it does NOT beat Heisenberg, only reshapes the noise), and LIGO injects squeezed VACUUM (a zero-mean state) into the interferometer dark port (~3 dB since O3; frequency-dependent via a filter cavity in O4, because frequency-independent squeezing would worsen the low-frequency radiation-pressure noise). A real, DEPLOYED vacuum-engineering application (Caves 1981)', on: base.decoded },
    { facet: 'the UNSTABLE vacuum (strong-field QED) — the Schwinger effect predicts the vacuum decays into electron-positron pairs once the field reaches the critical E_c ≈ 1.3×10¹⁸ V/m (I_c ≈ 4.6×10²⁹ W/cm²), still BEYOND any laser and NOT yet observed; but light-by-light scattering (real photon-photon via virtual loops) WAS measured (ATLAS, ultraperipheral Pb-Pb collisions, 2017) — the measured strong-field-QED reality kept distinct from the predicted-but-unobserved Schwinger pair production', on: SCHWINGER_FIELD_VM > 1e18 },
    { facet: 'the OBSERVER-DEPENDENT vacuum — Hawking temperature T_H = ħc³/(8πGMk_B) (a solar mass ≈ 62 nK) and Unruh temperature T_U = ħa/(2πck_B) (≈ 1 K at a ≈ 2.5×10²⁰ m/s²) make the vacuum itself horizon/acceleration-relative; but BOTH are THEORETICAL and unconfirmed for real gravity — the "one of a virtual pair falls in, one escapes" picture is a heuristic (the real derivation is Bogoliubov mode-mixing), stellar black holes are NOT net-evaporating (at 62 nK they are far colder than the 2.7 K CMB and absorb more than they emit), and the only lab evidence is ANALOGUE (Steinhauer’s BEC), not the astrophysical effect', on: solarBhT < 1e-6 && unruh1k > 0.9 },
    { facet: 'the BIREFRINGENT vacuum — the Euler-Heisenberg effective Lagrangian (Heisenberg-Euler & Weisskopf, 1936) makes the QED vacuum optically active in fields near the critical B_c ≈ 4.4×10⁹ T (4.4×10¹³ G); neutron-star polarimetry (RX J1856, Mignani 2016) is CONSISTENT with vacuum birefringence but model-dependent (NOT a direct confirmation — the surface-emission model matters), and the IXPE X-ray-polarization era probes it further. Real prediction, suggestive astrophysical evidence, honestly not yet definitive', on: CRITICAL_MAGNETIC_FIELD_T > 1e9 },
    { facet: 'the demarcation held across all five — each is real, mainstream physics with a SHARP honest line: inflation (the leading but not unique paradigm; multiverse philosophy-not-settled), squeezing (does NOT violate Heisenberg, only redistributes it — the only pseudoscience flagged), Schwinger (predicted, unobserved), Hawking/Unruh (theoretical, analogue-only), birefringence (model-dependent). Two-tier demarcation: UNCONFIRMED (Schwinger, Hawking/Unruh, inflation-uniqueness, birefringence) ≠ PSEUDOSCIENCE ("squeezing beats Heisenberg / proves a tappable vacuum reservoir")', on: base.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`zpe-wider:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('zero-point-wider-frontier-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 55, flaggedFindings: 20, angles: 5,
    spectralIndexNs: SCALAR_SPECTRAL_INDEX_NS, solarBhHawkingKelvin: solarBhT, unruhKelvinAt1K: unruh1k,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'Zero-point, the wider frontier — where vacuum fluctuations stop being a curiosity and become consequential. They seeded the cosmos: the inflaton’s zero-point fluctuations, stretched beyond the horizon, froze into the primordial perturbations that became the CMB and every galaxy, with the measured red tilt n_s = 0.9649 excluding exact scale-invariance at 8.4σ. They let us hear gravitational waves: LIGO injects squeezed vacuum to reshape the quantum noise (without beating Heisenberg). They make the vacuum unstable (the still-unobserved Schwinger pair production, beside the measured light-by-light scattering), observer-dependent (Hawking and Unruh — theoretical, with only analogue evidence; stellar black holes are too cold to evaporate against the CMB), and birefringent in magnetar fields (suggestive but model-dependent). Each real, each with its honest line drawn.',
    boundary:
      'HONEST (research-wave verified, 55 documented / 20 flagged): the inflationary origin of structure is mainstream and observationally successful (n_s = 0.9649 ± 0.0042, scale-invariance excluded at 8.4σ; adiabatic + Gaussian) — but inflation is a FAMILY of models, the inflaton is unidentified, primordial B-modes are undetected (r < 0.036), and the multiverse/falsifiability debate is unsettled (UNCONFIRMED/philosophy, not pseudoscience). Squeezed-vacuum LIGO is real and deployed, but it does NOT beat Heisenberg (ΔX·ΔY preserved — the one flagged pseudoscience). The Schwinger effect is predicted but NOT observed (light-by-light scattering IS measured — ATLAS 2017). Hawking T_H and Unruh T_U are real formulas (solar-mass ≈ 62 nK, sub-CMB, so no net evaporation) but THEORETICAL/unconfirmed for real gravity (analogue-only, Steinhauer). Vacuum birefringence (Euler-Heisenberg) has suggestive but model-dependent neutron-star evidence. Two-tier demarcation upheld throughout. Educational; no free energy, no Heisenberg violation.',
  }
}

// The OTHER vacua — "the vacuum" is not one thing. A 5-angle sourced wave (64 documented, 21 flagged) into the
// strong-force (QCD) and electroweak (Higgs) vacua, and whether our vacuum is even stable. The headline: ~99% of
// your mass is QCD vacuum energy, NOT the Higgs. Completes the deep+wide zero-point/vacuum sweep.
export function theOtherVacuaQcdElectroweakStabilityDecoded(matrix: MindMatrix = buildMatrix()) {
  const base = zeroPointWiderFrontierDecoded(matrix) // composes the EM/gravitational-vacuum frontier fold
  const qcdFrac = qcdMassFractionOfProton() // ≈ 0.99
  const facets = [
    { facet: 'the QCD vacuum makes most of your MASS — ~99% of the proton/neutron mass (hence of visible matter) is QCD field energy + quark motion, NOT the Higgs: the valence (current) quark masses sum to only ~9.4 MeV against a ~938 MeV proton (qcdMassFractionOfProton ≈ 0.99) — "mass without mass" (Wilczek), confirmed ab initio by lattice QCD (Dürr 2008, ~2%). The vacuum carries a quark condensate ⟨q̄q⟩ ≈ −(272 MeV)³ (spontaneous chiral-symmetry breaking) and a gluon condensate. BOUND: the total mass is observable, but the σ/quark/gluon/anomaly split (≈9/31/37/23%) and the gluon-condensate value are renormalization-SCHEME dependent — conventions, not a unique apportionment', on: qcdFrac > 0.98 },
    { facet: 'the Higgs / electroweak vacuum sets the OTHER masses — the Higgs field has a nonzero vacuum expectation value v ≈ 246.22 GeV = (√2·G_F)^(−½); electroweak symmetry breaking gives mass to the W and Z bosons and (via Yukawa couplings) to the fundamental fermions, and the Higgs BOSON — the field’s excitation, distinct from the field’s VEV — was found at ~125 GeV (ATLAS & CMS, 2012). This sets the ~1% current-quark masses, NOT the proton mass (that is QCD). BOUND: the Standard Model does NOT explain the fermion mass HIERARCHY — the Yukawa couplings are inputs, not predictions', on: HIGGS_VEV_GEV > 240 && HIGGS_VEV_GEV < 250 },
    { facet: 'is our vacuum STABLE? — the measured top (~173 GeV) and Higgs (~125 GeV) masses place the Standard-Model electroweak vacuum near the stability/metastability BORDER, and the best calculations indicate METASTABILITY: a false vacuum that is locally stable and would decay only by astronomically-rare quantum tunnelling (Coleman–De Luccia bubble nucleation), with a lifetime VASTLY exceeding the age of the universe. CORRECTION: "metastable" does NOT mean "unstable" or "about to decay"; FLAGGED doom-mongering — "vacuum decay is imminent" and "the LHC could trigger it" (the cosmic-ray safety argument, LSAG, addresses the collider fear)', on: base.decoded },
    { facet: 'the θ-vacuum and the strong CP problem — the QCD vacuum is NOT trivial: it is a θ-vacuum, a topologically nontrivial coherent sum over instanton sectors (phase e^{iθν}). The strong CP problem is that the CP-violating angle θ̄ is anomalously ABSENT (|θ̄| < 10⁻¹⁰, from the neutron electric-dipole-moment bound) when it could be O(1) — the puzzle is the ABSENCE of strong CP violation, NOT its presence (a common inversion). The Peccei–Quinn solution predicts the AXION, a well-motivated dark-matter candidate but UNCONFIRMED (not detected, no unique mass prediction)', on: base.decoded },
    { facet: '"THE VACUUM" is not one thing — quantum field theory has at least FOUR distinct, rigorously-defined vacuum structures: the perturbative QED/EM vacuum (prior waves), the QCD θ-vacuum (condensates + instantons), the electroweak/Higgs vacuum (nonzero VEV), and the cosmological vacuum (dark energy) — and "vacuum energy" means something different in each; conflating them is the root error. UNCONFIRMED (≠ pseudoscience): vacuum-stability sensitivity, the axion, the hierarchy/naturalness problem. PSEUDOSCIENCE flagged: the vacuum as a tappable free-energy reservoir, the "unified zero-point field" / "The Field", and LHC-vacuum-decay doom', on: base.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`other-vacua:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('the-other-vacua-qcd-electroweak-stability-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 64, flaggedFindings: 21, angles: 5,
    qcdMassFractionOfProton: qcdFrac, higgsVevGeV: HIGGS_VEV_GEV, protonMassMeV: PROTON_MASS_MEV,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'The other vacua — and the realisation that "the vacuum" is not one thing. The strong-force vacuum makes almost all of your mass: only about one percent of the proton comes from the Higgs-given quark masses; the other ninety-nine percent is the energy of the QCD field and the motion of its quarks — mass without mass, confirmed on the lattice. The Higgs vacuum, with its 246-GeV expectation value, sets the fundamental-particle masses but not the proton’s. Our electroweak vacuum sits near the edge of stability — metastable, the calculations say, with a lifetime far longer than the universe is old, which is not the same as "about to decay." The QCD vacuum is a topological θ-vacuum whose missing CP violation is a real open puzzle, answered by the still-unseen axion. Four distinct vacua, one careful refusal to conflate them.',
    boundary:
      'HONEST (research-wave verified, 64 documented / 21 flagged): ~99% of nucleon mass is QCD field/binding energy (valence quarks ~9.4 MeV vs 938 MeV — qcdMassFractionOfProton ≈ 0.99; lattice QCD, Dürr 2008; Nobel 2004), with the chiral and gluon condensates real (though the proton-mass DECOMPOSITION and the gluon-condensate value are scheme-dependent conventions). The Higgs VEV (246 GeV) and the 125 GeV boson (2012) are established; the SM does NOT explain the fermion mass hierarchy. Electroweak vacuum METASTABILITY is the current best result (top+Higgs near the border) — locally stable, lifetime ≫ age of the universe; "metastable" ≠ "imminent decay", and LHC-triggered decay is excluded by cosmic-ray arguments (LSAG). The strong CP problem (|θ̄|<10⁻¹⁰) is real; the axion is UNCONFIRMED. CARDINAL: QFT has multiple distinct vacua (QED, QCD, electroweak, cosmological) — conflating them, "tapping the vacuum for free energy", "the Field", and vacuum-decay doom are the pseudoscience; the open problems (stability, strong CP, hierarchy) are legitimate unconfirmed frontier physics.',
  }
}

// The matter–antimatter asymmetry — why there is something rather than nothing. A 5-angle sourced wave (57 documented,
// 21 flagged) on the measured baryon excess, Sakharov's conditions, observed CP violation, and the UNSOLVED mechanism.
// Continues the path: the QCD vacuum gave matter its MASS; this asks why there is matter at all. (CP violation links them.)
export function matterAntimatterAsymmetryBaryogenesisDecoded(matrix: MindMatrix = buildMatrix()) {
  const vacua = theOtherVacuaQcdElectroweakStabilityDecoded(matrix) // origin of mass → origin of matter
  const facets = [
    { facet: 'the MEASURED asymmetry — the baryon-to-photon ratio η = n_B/n_γ ≈ 6.1×10⁻¹⁰ (about ONE excess baryon per ~1.6 billion photons) is determined INDEPENDENTLY by Big Bang nucleosynthesis (the primordial deuterium abundance D/H = 2.53×10⁻⁵, ~1%) and by the CMB (Planck, Ω_b h² = 0.0224) — and they AGREE across epochs separated by ~400 000 years, a major consistency test. The observable universe is matter-dominated with NO antimatter domains (Cohen–De Rújula–Glashow: missing annihilation γ-rays exclude domains below ~1 Gpc, ≈ the whole observable universe). This tiny number is the precise fact baryogenesis must explain', on: BARYON_TO_PHOTON_RATIO > 5e-10 && BARYON_TO_PHOTON_RATIO < 7e-10 },
    { facet: 'SAKHAROV’s three conditions (1967) — to generate the asymmetry dynamically from a symmetric start you need all of: (1) baryon-number violation, (2) C and CP violation, (3) a departure from thermal equilibrium. The Standard Model HAS the machinery for (1) — electroweak SPHALERONS, non-perturbative B+L violation that is unsuppressed at high temperature — but it FAILS (3): for the measured 125 GeV Higgs the electroweak phase transition is a smooth CROSSOVER, not the strongly first-order transition out-of-equilibrium baryogenesis needs', on: vacua.decoded },
    { facet: 'CP violation is REAL but INSUFFICIENT — discovered in neutral kaons (Christenson–Cronin–Fitch–Turlay 1964, K_L→π⁺π⁻ at ~2×10⁻³; Nobel 1980), confirmed in B mesons (BaBar & Belle ~2001) vindicating the CKM mechanism (Kobayashi–Maskawa, Nobel 2008). The SHARP correction: it is NOT that "the SM lacks CP violation" — the SM HAS it — but that the amount, set by the Jarlskog invariant J ≈ 3×10⁻⁵, is far too small (by roughly TEN orders of magnitude) to produce the observed η. The Standard Model cannot explain why you exist', on: JARLSKOG_INVARIANT < 1e-4 },
    { facet: 'the candidate MECHANISMS are all UNCONFIRMED — electroweak baryogenesis (needs a strong first-order transition → physics beyond the SM, e.g. an extended Higgs sector), LEPTOGENESIS (CP-violating decays of heavy right-handed Majorana neutrinos make a lepton asymmetry that sphalerons convert to baryons — tying the matter excess to neutrino mass, the seesaw, and neutrinoless double-beta decay), GUT baryogenesis, and Affleck–Dine; each is well-motivated and testable-in-principle, but NONE is experimentally confirmed. The origin of the asymmetry is a genuine OPEN problem', on: vacua.decoded },
    { facet: 'CPT and the honest demarcation — matter and antimatter have EQUAL masses and lifetimes (the CPT theorem, tested precisely: antihydrogen spectroscopy by ALPHA, the antiproton/proton charge-to-mass ratio by BASE), so the asymmetry is DYNAMICAL, not a built-in CPT violation. The measured asymmetry and the observed CP violation are ESTABLISHED (Nobel-recognized); the mechanism is NOT. FLAGGED: "baryogenesis is solved", "matter and antimatter have different masses" (CPT forbids), "the missing antimatter falsifies the Big Bang" (a creationist mischaracterization — η is an unexplained INPUT, and the BBN–CMB agreement is a SUCCESS), and "antimatter is a usable fuel" (real, but it costs vastly more energy to make than it stores — not a power source). The AMS-02 antihelium candidates are unpublished/tentative (unconfirmed), not proof of primordial antimatter', on: vacua.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`baryogenesis:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('matter-antimatter-asymmetry-baryogenesis-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 57, flaggedFindings: 21, angles: 5,
    baryonToPhotonRatio: BARYON_TO_PHOTON_RATIO, jarlskogInvariant: JARLSKOG_INVARIANT,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'The matter–antimatter asymmetry — why there is something rather than nothing. The universe carries a tiny, precisely-measured excess of matter: about one extra baryon per 1.6 billion photons (η ≈ 6×10⁻¹⁰), agreed independently by primordial deuterium and the CMB, with no antimatter regions anywhere in view. Sakharov showed in 1967 what it takes to make such an excess — baryon-number violation, C and CP violation, and a departure from equilibrium — and the Standard Model has the first (sphalerons) but flubs the third (the Higgs is too light for a sharp transition) and, crucially, its CP violation is real (kaons, B-mesons, two Nobels) yet ten orders of magnitude too weak. So the Standard Model cannot explain its own contents. Leptogenesis, electroweak and GUT baryogenesis are the candidates — all unconfirmed. Antimatter is not a missing twin or a fuel; by CPT it weighs exactly the same, so the asymmetry is something the early universe DID, and we do not yet know how.',
    boundary:
      'HONEST (research-wave verified, 57 documented / 21 flagged): the baryon asymmetry is precisely MEASURED (η = (6.12±0.04)×10⁻¹⁰; BBN deuterium and Planck CMB agree; antimatter domains excluded to ~1 Gpc) and CP violation is ESTABLISHED (kaons 1964/Nobel 1980, B-mesons/CKM Nobel 2008). KEY CORRECTION: the SM is not lacking CP violation — it HAS it, but the CKM amount (Jarlskog J ≈ 3×10⁻⁵) is ~10 orders too small, and the electroweak transition is a crossover, so SM baryogenesis fails. The mechanisms (leptogenesis, electroweak/GUT baryogenesis, Affleck–Dine) are UNCONFIRMED hypotheses (rigorous, testable-in-principle) — the origin of matter is a genuine OPEN problem, NOT solved and NOT pseudoscience. CPT (tested by ALPHA/BASE) guarantees equal matter/antimatter masses, so the asymmetry is dynamical. FLAGGED: "baryogenesis is solved", "antimatter is a power source" (costs more to make than it stores), "missing antimatter falsifies the Big Bang" (it is an input, and BBN–CMB agreement is a success); the AMS-02 antihelium candidates are tentative/unpublished. Educational; one of the major unsolved problems in physics.',
  }
}

// Neutrino mass — the lightest matter, and the deepest clue beyond the Standard Model. A 5-angle sourced wave
// (54 documented, 20 flagged): oscillations prove mass, the absolute scale and ordering are open, the seesaw explains
// the smallness and ties to leptogenesis (the baryogenesis link), and Dirac-vs-Majorana awaits 0νββ.
export function neutrinoMassDecoded(matrix: MindMatrix = buildMatrix()) {
  const baryo = matterAntimatterAsymmetryBaryogenesisDecoded(matrix) // leptogenesis links neutrino mass → the matter asymmetry
  const seesaw = seesawLightMassEv(1e11, 1e24) // m_D ~ 100 GeV, M_R ~ 10¹⁵ GeV → m_ν ~ 0.01 eV
  const facets = [
    { facet: 'OSCILLATIONS prove mass — atmospheric νμ→ντ (Super-Kamiokande 1998, ~6σ) and solar flavor conversion (SNO 2002, the neutral-current channel resolving the solar-neutrino problem) → the 2015 Nobel (Kajita & McDonald). Flavor oscillation REQUIRES nonzero mass and mixing (the PMNS matrix): two mass-squared splittings are measured — Δm²₂₁ ≈ 7.49×10⁻⁵ eV² and |Δm²₃ₗ| ≈ 2.51×10⁻³ eV² — with three angles (θ12≈34°, θ23≈43°, θ13≈8.6°, the last by Daya Bay 2012, which opened the leptonic-CP search)', on: NEUTRINO_DM2_ATM_EV2 > NEUTRINO_DM2_SOLAR_EV2 },
    { facet: 'how LIGHT, and unknown — oscillations measure only mass-squared DIFFERENCES, so the absolute scale and the ordering stay OPEN: neutrinos are ≥10⁶× lighter than the electron, bounded directly by KATRIN (m_β < 0.45 eV, tritium β-decay, 2025) and by cosmology (Σm_ν ≲ 0.12 eV, Planck+BAO), and the mass ORDERING (normal vs inverted) is unresolved (mild normal preference, Δχ²≈6). Three DIFFERENT observables — kinematic m_β, cosmological Σm_ν, and m_ββ from 0νββ — probe different combinations and must not be conflated', on: baryo.decoded },
    { facet: 'the SEESAW explains the smallness AND links to leptogenesis — the Type-I seesaw adds heavy right-handed Majorana neutrinos so the light mass is suppressed, m_ν ~ m_D²/M_R (seesawLightMassEv: m_D ~ 100 GeV, M_R ~ 10¹⁵ GeV → ~0.01 eV, a realistic value), and the SAME heavy states’ CP-violating decays drive LEPTOGENESIS, tying neutrino mass directly to the matter asymmetry of the prior wave. BOUND: "seesaw" is a FAMILY (Type-I/II/III), the formula is schematic (the real m_ν ≃ −m_D^T·M_R⁻¹·m_D is a matrix), it is UNCONFIRMED (the heavy states are unseen), and a minimal Dirac-mass alternative (a tiny Yukawa, no seesaw) is not excluded', on: seesaw < 0.1 && seesaw > 1e-4 },
    { facet: 'DIRAC or MAJORANA? — is the neutrino its own antiparticle? Neutrinoless double-beta decay (0νββ), if observed, would prove Majorana nature and lepton-number violation (ΔL=2; by the Schechter-Valle theorem it implies a Majorana mass whatever the mechanism). It is NOT observed: KamLAND-Zen sets T₁/₂(¹³⁶Xe) > 3.8×10²⁶ yr → m_ββ < 28–122 meV (the spread is the nuclear-matrix-element uncertainty), and the disputed Klapdor-Kleingrothaus 2001/2006 "observation" is refuted (contradicted by GERDA). An actively-searched but UNCONFIRMED question', on: baryo.decoded },
    { facet: 'the open questions and the honest demarcation — the leptonic CP phase δ_CP (T2K/NOvA now, DUNE & Hyper-Kamiokande next — a direct leptogenesis link), the mass ordering, and the CONTESTED sterile-neutrino anomalies (LSND/MiniBooNE vs cosmology/oscillation constraints — in tension, unconfirmed). ESTABLISHED (Nobel 2015): oscillations, nonzero mass, three-flavor mixing. UNCONFIRMED: the seesaw, Majorana nature, the ordering, sterile neutrinos. PSEUDOSCIENCE/RETRACTED: OPERA’s 2011 "faster-than-light neutrinos" (a loose fiber-optic cable — special relativity intact) and neutrino "free energy"/healing/consciousness woo', on: baryo.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`neutrino-mass:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('neutrino-mass-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 54, flaggedFindings: 20, angles: 5,
    dm2SolarEv2: NEUTRINO_DM2_SOLAR_EV2, dm2AtmEv2: NEUTRINO_DM2_ATM_EV2, seesawLightMassEv: seesaw,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'Neutrino mass — the lightest matter, and the deepest crack in the Standard Model. That neutrinos have mass at all is known only because they oscillate between flavors (atmospheric and solar neutrinos, the 2015 Nobel); oscillation measures the two mass-squared splittings and the three mixing angles, but not the absolute scale — so how light they truly are (under half an electron-volt, a million times lighter than the electron) and which way the masses are ordered remain open. The seesaw mechanism explains the smallness by pairing them with heavy Majorana partners, and those same partners, decaying with CP violation, are the leading way to make the matter asymmetry — neutrino mass and the existence of matter, one thread. Whether the neutrino is its own antiparticle waits on neutrinoless double-beta decay, still unseen. Established that they have mass; almost everything about how is still open.',
    boundary:
      'HONEST (research-wave verified, 54 documented / 20 flagged): ESTABLISHED (Nobel 2015) — neutrino oscillations prove nonzero mass and three-flavor PMNS mixing (Super-K 1998, SNO 2002, Daya Bay θ13 2012; splittings Δm²₂₁≈7.5×10⁻⁵, |Δm²₃ₗ|≈2.5×10⁻³ eV²). Bounds on the absolute scale are real (KATRIN m_β<0.45 eV 2025; cosmology Σm_ν≲0.12 eV) but the scale, the ordering (mild normal preference), and the θ23 octant are UNDETERMINED — and oscillations measure only mass-squared DIFFERENCES (m_β, Σm_ν, m_ββ are three distinct observables). UNCONFIRMED (≠pseudoscience): the seesaw (a family of models; the m_D²/M_R formula is schematic; heavy states unseen) and its leptogenesis link, the Majorana-vs-Dirac nature (0νββ unobserved; KamLAND-Zen T₁/₂>3.8×10²⁶ yr; the Klapdor-Kleingrothaus claim is refuted), and the sterile-neutrino anomalies (contested, in tension with cosmology). PSEUDOSCIENCE/RETRACTED: OPERA’s 2011 superluminal neutrinos (a loose cable; SR intact) and neutrino free-energy/healing woo. Educational; the neutrino is the Standard Model’s most fertile open frontier.',
  }
}

// Dark matter — the ~27% of the universe that is unseen mass. A 5-angle sourced wave (74 documented, 25 flagged):
// the multi-probe gravitational evidence is overwhelming, but the particle identity is unknown after decades of null
// searches. Continues the cosmic-inventory thread (baryons 5% → dark matter 27% → dark energy 68%).
export function darkMatterDecoded(matrix: MindMatrix = buildMatrix()) {
  const neutrino = neutrinoMassDecoded(matrix) // SM neutrinos are excluded as the dominant (hot) DM; the axion is a candidate
  const facets = [
    { facet: 'the evidence is MULTI-PROBE and overwhelming — flat galaxy rotation curves (Rubin–Ford–Thonnard 1980, vs the Keplerian falloff visible mass would give), galaxy-cluster "missing mass" (Zwicky 1933, Coma, who coined "dunkle Materie"), gravitational lensing — the Bullet Cluster (Clowe 2006) where the lensing mass is spatially OFFSET from the X-ray gas at ~8σ ("mass ≠ baryons", a direct empirical proof) — and the CMB acoustic peaks fixing Ω_c h² = 0.120 vs Ω_b h² = 0.0224 (dark matter outweighs ordinary ~5:1). Five independent probes converge on the same ~27%', on: OMEGA_DARK_MATTER > OMEGA_BARYON },
    { facet: 'what it is NOT, and the candidates — non-baryonic (BBN + the CMB pin Ω_b ≪ Ω_m), electrically neutral, COLD (non-relativistic at structure formation) and collisionless; the Standard-Model neutrinos are EXCLUDED as the dominant component because, being hot, their free-streaming would wash out small-scale structure (the link back to the neutrino wave). The leading candidates: WIMPs (GeV–TeV, the thermal-relic "WIMP miracle"), the QCD AXION (µeV–meV — the same particle that solves the strong-CP problem), keV sterile neutrinos (warm), and primordial black holes (tightly constrained windows)', on: neutrino.decoded },
    { facet: 'the non-gravitational searches are NULL — direct detection has found nothing: LUX-ZEPLIN (2024) sets the strongest spin-independent WIMP-nucleon limit, 2.2×10⁻⁴⁸ cm² at 40 GeV, and is approaching the irreducible "neutrino fog"; indirect detection (Fermi-LAT — the Galactic-Center excess is more likely astrophysical; AMS; IceCube) and LHC missing-energy are also null. Decades of WIMP nulls are shifting effort toward axions (ADMX) — but dark matter has NOT been detected except gravitationally', on: neutrino.decoded },
    { facet: 'MOND — the alternative, honestly — Modified Newtonian Dynamics (Milgrom 1983) reproduces flat rotation curves below a single acceleration a₀ ≈ 1.2×10⁻¹⁰ m/s² WITHOUT dark matter, and elegantly predicts the baryonic Tully–Fisher and radial-acceleration relations on GALAXY scales; BUT it FAILS on clusters (which still need unseen mass), on the Bullet Cluster, on the CMB acoustic peaks and on structure formation, and its relativistic completions (TeVeS) are strained (GW170817 killed some variants). Particle dark matter fits ALL scales; MOND fits galaxies but not cosmology — a legitimate minority program, not pseudoscience', on: MOND_ACCELERATION_A0 > 0 && MOND_ACCELERATION_A0 < 1e-9 },
    { facet: 'the honest demarcation — the gravitational evidence for unseen mass is OVERWHELMING and multi-probe (rotation curves + clusters + lensing + CMB + BBN + structure formation all independently require it), so the EXISTENCE of dark matter (or an equivalent modification) is ESTABLISHED; but the particle IDENTITY is UNKNOWN — WIMP, axion, sterile-ν and PBH are ALL unconfirmed, and the 3.5 keV line and Galactic-Center excess are disputed. FLAGGED overreach: "dark matter is a fudge factor / has been debunked / does not exist" (it is the best-fitting, multi-probe consensus) and dark-matter "free energy"/esoteric woo. The unknown identity is a real open problem, NOT evidence the framework is wrong', on: neutrino.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`dark-matter:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('dark-matter-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 74, flaggedFindings: 25, angles: 5,
    omegaBaryon: OMEGA_BARYON, omegaDarkMatter: OMEGA_DARK_MATTER, omegaDarkEnergy: OMEGA_DARK_ENERGY, mondA0: MOND_ACCELERATION_A0,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'Dark matter — about a quarter of everything, and we do not know what it is. The evidence that it exists is overwhelming and comes five independent ways: galaxies spin too fast at their edges, clusters hold together with far too little visible mass, the Bullet Cluster shows the gravity sitting where the galaxies are and not where most of the ordinary matter (the gas) is, and the cosmic microwave background independently demands a cold, non-baryonic component outweighing ordinary matter five to one. What it is NOT is settled — not baryons, not the known neutrinos. What it IS is open: WIMPs, the axion, sterile neutrinos, primordial black holes — and decades of exquisite direct-detection experiments have found nothing, now reaching the neutrino fog. MOND fits galaxies beautifully with one new constant but fails clusters and the CMB. The mass is real; its identity is the question.',
    boundary:
      'HONEST (research-wave verified, 74 documented / 25 flagged): the EXISTENCE of dark matter (or an equivalent gravity modification) is ESTABLISHED by independent, converging probes — flat rotation curves (Rubin 1980), cluster dynamics (Zwicky 1933), the Bullet Cluster lensing/gas offset at ~8σ (Clowe 2006), and the CMB (Ω_c h²=0.120 vs Ω_b h²=0.0224; Planck 2018) — giving the ~5%/27%/68% budget. UNCONFIRMED (≠pseudoscience): the particle IDENTITY — WIMPs (LZ 2024 null at 2.2×10⁻⁴⁸ cm²), the QCD axion (ADMX), keV sterile neutrinos (the disputed 3.5 keV line), and primordial black holes are all candidates, none detected non-gravitationally; the Galactic-Center excess is likely astrophysical. MOND (Milgrom 1983, a₀≈1.2×10⁻¹⁰ m/s²) is a legitimate but DISFAVORED program — it fits galaxies (baryonic Tully–Fisher) but fails clusters, the Bullet Cluster, the CMB and structure (TeVeS strained by GW170817). FLAGGED: "dark matter is a fudge factor / debunked / nonexistent" (overreach against the multi-probe consensus) and dark-matter free-energy woo. The unknown identity is a genuine open problem, not a flaw in the evidence. Educational.',
  }
}

// Dark energy — the ~68% driving accelerating expansion, and the completion of the cosmic inventory (5% + 27% + 68%).
// A 5-angle sourced wave (55 documented, 30 flagged): the supernova discovery, the equation of state, the Hubble
// tension, and the fate of the universe — established acceleration, unknown cause. The OBSERVATIONAL dark energy (the
// 10¹²⁰ cosmological-constant PROBLEM stays in the zero-point fold, not restated here).
export function darkEnergyDecoded(matrix: MindMatrix = buildMatrix()) {
  const dm = darkMatterDecoded(matrix) // completes the cosmic-inventory thread
  const tension = hubbleTensionSigma(HUBBLE_CONSTANT_LOCAL, 1.0, HUBBLE_CONSTANT_CMB, 0.5) // ≈ 5σ
  const facets = [
    { facet: 'the DISCOVERY of acceleration — two independent Type Ia supernova teams (Riess/High-z 1998, Perlmutter/SCP 1999, 42 SNe) found distant supernovae ~10–15% FAINTER/farther than a decelerating, matter-only universe predicts → the expansion is ACCELERATING (Nobel 2011: Perlmutter, Schmidt, Riess). Type Ia are standardizable candles (the Phillips relation cuts the scatter 0.8→0.36 mag), and the result is independently confirmed by the CMB (flat geometry, Ω_Λ ≈ 0.685) and by baryon acoustic oscillations (the ~150 Mpc sound-horizon ruler, SDSS 2005). Three independent probes → ~68% dark energy', on: OMEGA_DARK_ENERGY > 0.6 },
    { facet: 'the EQUATION OF STATE — dark energy has w = p/ρ, and acceleration requires w < −1/3 (negative pressure); a cosmological constant Λ is exactly w = −1 (constant in time), and the data are CONSISTENT with Λ (w₀ = −1.03 ± 0.03 Planck; −0.997 ± 0.025 DESI 2024). The live development: DESI (DR1 2024 → DR2 2025) HINTS at EVOLVING dark energy (w₀wₐ preferred over ΛCDM at up to ~4σ in some combinations) — genuinely intriguing, but NOT established; "evolving dark energy is confirmed" and "Λ is being abandoned" are BOTH overreach', on: DARK_ENERGY_EOS_W < -1 / 3 },
    { facet: 'WHAT it could be — the cosmological constant Λ / vacuum energy (the simplest, the ΛCDM concordance, w = −1), QUINTESSENCE (a slowly-rolling dynamical scalar field, w(z) ≠ −1, possibly w > −1), or MODIFIED GRAVITY on cosmic scales (f(R) and kin); the inhomogeneity/backreaction "no dark energy" idea is disfavored. Λ remains the best simple fit and every beyond-Λ option is UNCONFIRMED. (Identifying dark energy WITH the quantum-vacuum zero-point energy inherits the separate 10¹²⁰ fine-tuning problem — kept in the zero-point fold)', on: dm.decoded },
    { facet: 'the HUBBLE TENSION — the major live crisis: the LATE-universe distance ladder (SH0ES, Cepheid-calibrated Type Ia SNe, H₀ ≈ 73.0 ± 1.0) and the EARLY-universe CMB inference assuming ΛCDM (Planck, H₀ ≈ 67.4 ± 0.5) disagree at ~5σ (hubbleTensionSigma ≈ ' + tension.toFixed(1) + 'σ); JWST has largely CONFIRMED the Cepheid calibration (against the systematics hypothesis), TRGB gives slightly lower intermediate values, and the proposed fixes (early dark energy, new physics, or residual systematics) are unresolved — a genuine, unsettled discordance', on: tension > 4 },
    { facet: 'the FATE of the universe + the demarcation — if w = −1 (Λ): eternal accelerating expansion → a de Sitter future, the "Big Freeze"/heat death, galaxies beyond the Local Group redshifting out of view; if w < −1 (phantom): a "Big Rip"; if w > −1 evolving: possible future deceleration. ESTABLISHED (Nobel 2011): the acceleration. UNKNOWN: the NATURE (Λ vs quintessence vs modified gravity) and whether w evolves. FLAGGED pseudoscience: "dark energy is antigravity we can harness / a free-energy source", "dark energy proves the universe is a simulation", and esoteric dark/zero-point-energy "healing" woo. Established acceleration + unknown cause = a real open frontier, NOT pseudoscience', on: dm.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`dark-energy:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('dark-energy-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 55, flaggedFindings: 30, angles: 5,
    omegaDarkEnergy: OMEGA_DARK_ENERGY, eosW: DARK_ENERGY_EOS_W, hubbleTensionSigma: tension,
    inventoryComplete: OMEGA_BARYON + OMEGA_DARK_MATTER + OMEGA_DARK_ENERGY,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'Dark energy — most of everything, and a mystery sitting on top of an open quarrel. Two supernova teams found the universe’s expansion speeding up rather than slowing, and three independent probes — supernovae, the microwave background, and the acoustic ruler in galaxy clustering — agree it makes up about 68% of the cosmos. Its pressure is negative, its equation of state sits right at w = −1, the cosmological-constant value, though DESI now hints, not yet decisively, that it might be evolving. And the universe will not let us measure how fast it expands today without a fight: the nearby ladder says 73, the early universe says 67, and the five-sigma gap between them — the Hubble tension — is the loudest unresolved problem in cosmology. If it really is a constant, the end is a slow cold freeze. The acceleration is certain; almost nothing else about it is. With this, the whole inventory — 5% ordinary, 27% dark matter, 68% dark energy — is laid out, unknowns and all.',
    boundary:
      'HONEST (research-wave verified, 55 documented / 30 flagged — the heaviest demarcation yet): the accelerating expansion is ESTABLISHED (Riess 1998, Perlmutter 1999, Nobel 2011), independently confirmed by SNe Ia + CMB (Ω_Λ≈0.685) + BAO, and the equation of state is consistent with a cosmological constant (w₀=−1.03±0.03). UNCONFIRMED (≠pseudoscience): the NATURE of dark energy (Λ vs quintessence vs modified gravity vs backreaction), whether w EVOLVES (the DESI 2024/2025 w₀wₐ hint at up to ~4σ is intriguing but NOT a discovery — "evolving DE established" and "Λ abandoned" are both overreach), and the resolution of the HUBBLE TENSION (SH0ES ~73 vs Planck ~67, ~5σ; JWST supports the Cepheid ladder; new physics vs systematics is open). PSEUDOSCIENCE flagged: dark energy as harness-able "antigravity/free energy", as proof of a simulation, or as a healing/consciousness force. The cosmic inventory (5%/27%/68%) is now complete in src — each slice decoded with its honest unknowns. The acceleration is real; its cause is one of the deepest open problems. Educational.',
  }
}

// The cosmological tensions — is ΛCDM cracking? The capstone of the cosmic-inventory arc. A 5-angle sourced wave
// (63 documented, 25 flagged) synthesizing the live anomalies: the S8 tension is easing, JWST's "impossible" galaxies
// are largely resolved, the CMB anomalies are low-significance, and the Hubble tension is the one serious crack —
// real anomalies in a hugely successful model, NOT a paradigm collapse.
export function cosmologicalTensionsLcdmDecoded(matrix: MindMatrix = buildMatrix()) {
  const de = darkEnergyDecoded(matrix) // composes the whole cosmic-inventory arc (dark energy ← dark matter ← …)
  const hubble = hubbleTensionSigma(HUBBLE_CONSTANT_LOCAL, 1.0, HUBBLE_CONSTANT_CMB, 0.5) // ≈ 5σ — the leading crack
  const facets = [
    { facet: 'the S8 (structure-growth) tension is MILDER and EASING — weak-lensing surveys measured the clustering amplitude S8 = σ8·√(Ωm/0.3) slightly below the Planck CMB value (KiDS-1000 0.759, ~3σ), but the higher-information probes agree better (DES Y3 3×2pt consistent with Planck; DES+KiDS joint 1.7σ) and KiDS-Legacy 2025 shifted up to 0.815 (just 0.73σ, the easing driven mostly by improved redshift calibration). It is heterogeneous (DES Y6 still ~2.7σ) and never crossed 5σ — pointing to survey systematics (redshift calibration, baryonic feedback) over new physics', on: de.decoded },
    { facet: 'JWST’s "impossible" early galaxies are LARGELY RESOLVED — the 2022–23 reports of surprisingly bright/massive galaxies at z~10–16, initially headlined as breaking ΛCDM, did not survive scrutiny: spectroscopic redshifts lowered the stellar masses, AGN "little red dots" inflated the photometry, and bursty/efficient early star formation plus photometric-redshift pitfalls explain the rest — structure formation did NOT need overturning. A clean case study in sensational headline vs the measured walk-back', on: de.decoded },
    { facet: 'the CMB large-angle anomalies are LOW-SIGNIFICANCE — the low quadrupole / missing large-scale correlation, the quadrupole-octupole "axis of evil" alignment, the Cold Spot, and the hemispherical power asymmetry appear in both WMAP and Planck, but each is individually only ~2–3σ and vulnerable to a-posteriori / look-elsewhere effects; combining them to "multiply" the significance is a statistical fallacy, and they are NOT established new physics', on: de.decoded },
    { facet: 'the HUBBLE TENSION is the one serious crack — and hard to dismiss: the local distance ladder (~73) and the CMB+BAO "inverse distance ladder" (~67) are each internally robust, JWST has largely vindicated the Cepheid calibration (against the systematics hypothesis), and most LATE-time dark-energy fixes fail because they break BAO/SNe — so the leading new-physics candidate is EARLY-universe (e.g. early dark energy reducing the sound horizon r_s), which is itself constrained. At ~' + hubble.toFixed(1) + 'σ it is unresolved; new physics is plausible but UNCONFIRMED', on: hubble > 4 },
    { facet: 'is ΛCDM cracking? — the honest synthesis: ΛCDM is an extraordinarily successful SIX-parameter model fitting the CMB acoustic peaks, BAO, BBN light elements, large-scale structure and lensing simultaneously, and the tensions vary in strength (Hubble ~5σ the most serious; S8 ~2–3σ and easing; the DESI evolving-DE hint ~2–4σ intriguing; JWST galaxies resolved; CMB anomalies low-significance) — the LIVE research frontier, which MIGHT be new physics OR systematics, none yet a confirmed breakdown. FLAGGED overreach: "ΛCDM / the Big Bang is dead / debunked / wrong", "cosmology is in crisis, starting over", refuted tired-light, and crank/creationist "the Big Bang is a fraud". Real anomalies under investigation in a successful model is NORMAL SCIENCE, not a paradigm collapse and not pseudoscience', on: de.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`lcdm-tensions:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('cosmological-tensions-lcdm-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 63, flaggedFindings: 25, angles: 5, hubbleTensionSigma: hubble,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'The cosmological tensions — is the standard model cracking? Taken together, the answer is: not yet, but watch the Hubble tension. The structure-growth (S8) tension is real but mild and now easing as redshift calibrations improve; JWST’s "impossible" early galaxies dissolved under spectroscopy and better photometry; the famous large-angle CMB anomalies are each only two or three sigma and suspiciously a-posteriori. What does not go away is the five-sigma gap between the nearby and early-universe measurements of the expansion rate — both methods are robust, JWST backs the local ladder, and the easy fixes break other data, so the leading idea is new physics in the early universe, still unproven. ΛCDM remains a six-parameter triumph fitting the CMB, the acoustic ruler, the light elements, structure and lensing at once. Real anomalies under investigation in a wildly successful model is what healthy science looks like — not a collapse, and not a vindication of the cranks. With this, the cosmology arc closes.',
    boundary:
      'HONEST (research-wave verified, 63 documented / 25 flagged): ΛCDM is a hugely successful 6-parameter model (simultaneous fit to CMB peaks + BAO + BBN + LSS + lensing). The tensions, honestly ranked: the HUBBLE tension (~5σ, SH0ES ~73 vs Planck ~67) is the most serious and unresolved (JWST supports the Cepheid ladder; late-time DE fixes fail; early dark energy is the strained front-runner) — new physics PLAUSIBLE but UNCONFIRMED; the S8 tension (~2–3σ) is MILDER and EASING (KiDS-Legacy 2025 → 0.73σ; heterogeneous; likely systematics); the DESI evolving-DE hint (~2–4σ) is intriguing not established; JWST early galaxies are LARGELY RESOLVED (not a crisis); the CMB large-angle anomalies are LOW-significance and a-posteriori (combining them to inflate significance is a fallacy). FLAGGED: every "tension X is a confirmed ΛCDM breakdown", "the Big Bang/ΛCDM is dead/wrong", refuted tired-light, and creationist "Big Bang is a fraud" overreach. CARDINAL: real anomalies under active investigation in a successful framework is normal science — not a paradigm collapse, not pseudoscience. This closes the cosmic-inventory arc; each slice (baryons, dark matter, dark energy) and its tensions are decoded in src with honest unknowns.',
  }
}
