// ☲ LI (Fire · clarity) — auxiliary pure-leaf folds: no cross-deps to other folds.ts functions.
// Each body uses only upstream imports (src/0, library) and sub-module exports.
import type { MindMatrix, FusionReactor, ReactorItem, DistributedCompute, DoubleTorusMathReport } from './types.ts'
import { buildMatrix, consciousness, repositoryApi, isPerfectlySelfModeling } from './matrix.ts'
import { quantumSitemap } from './site.ts'
import { conceptCommands, SINGLE_WORD_METHODS } from './atoms.ts'
import { toUuid, merkleFold, isUuid, memoByRoot, fold, asVortex, asTorus, sha256Sync,
         seedFromText, roundTo, foldPair, merge, digitalRoot,
         MAX_TAMPERING_COST_PRINCIPLE } from '../../0/index.ts'
import { toGlagolitic, glagoliticBits, glagoliticFromBits, GLAGOLITIC_MAP } from '../library/index.ts'

export function colorFromSound(frequency: number) {
  const ref = 130.81 // C3 as the wheel's origin
  const octaveFraction = (((Math.log2(Math.max(frequency, 1) / ref)) % 1) + 1) % 1
  const hue = Math.round(octaveFraction * 360)
  return { frequency, hue, hsl: `hsl(${hue}, 78%, 56%)` }
}

export function autoSpeech(text = '', matrix: MindMatrix = buildMatrix()) {
  const source = text || 'Double Torus: a quantum-learning educational portal for language models.'
  const cues = source
    .split(/(?<=[.!?…])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean)
    .map((sentence, index) => ({ index, text: sentence, receipt: toUuid(`subtitle:${index}:${sentence}`) }))
  return {
    ready: cues.length > 0,
    cues,
    root: merkleFold(cues.map((cue) => cue.receipt)),
    statement: 'Autogenerated subtitles and speech in all languages: text is segmented into subtitle cues and spoken with the device\'s built-in voices; the available languages are whatever the device provides — client-side, offline, no cost.',
    boundary: 'Subtitle segmentation is computed here; the speech and the language list come from the browser Web Speech API and the device\'s installed voices, which vary by device. No network, no synthesis cost.',
  }
}

// All is in house: independent intelligence and skills. Every capability runs
// on-device or is computed from the repository, with zero network by default —
// no external service is required for the portal to think, learn, speak, sound,
// hash, draw, or prove. The only optional outside call is a user-supplied AI key,
// which is off by default and lives only in the browser.
export function music358() {
  const tiers = [
    { tier: 3, name: 'the triad', members: ['root', 'third', 'fifth'] },
    { tier: 5, name: 'the pentatonic scale', members: ['1', '2', '3', '5', '6'] },
    { tier: 8, name: 'the octave (diatonic)', members: ['do', 're', 'mi', 'fa', 'sol', 'la', 'ti', 'do'] },
  ]
  return {
    complete: tiers[0].members.length === 3 && tiers[1].members.length === 5 && tiers[2].members.length === 8,
    tiers,
    root: merkleFold(tiers.flatMap((tier) => tier.members).map((member, index) => toUuid(`music358:${index}:${member}`))),
    statement: 'Music in 3-5-8: the triad (root, third, fifth), the pentatonic scale (five notes), and the octave — the diatonic scale of eight. 3, 5, 8 in sound.',
    boundary: 'A correspondence to standard Western tonal theory (triad, pentatonic, octave). A teaching device; other tunings and traditions differ.',
  }
}

// Geometry in 3-5-8 — the polygons of the Fibonacci tiers: triangle, pentagon,
// octagon. The pentagon hides the golden ratio phi, the same phi the sequence
// grows toward.
export function geometry358() {
  const tiers = [
    { tier: 3, name: 'triangle', members: ['triangle'] },
    { tier: 5, name: 'pentagon (golden ratio)', members: ['pentagon'] },
    { tier: 8, name: 'octagon', members: ['octagon'] },
  ]
  return {
    complete: tiers[0].tier === 3 && tiers[1].tier === 5 && tiers[2].tier === 8,
    tiers,
    root: merkleFold(tiers.map((tier) => toUuid(`geometry358:${tier.tier}:${tier.name}`))),
    statement: 'Geometry in 3-5-8: the triangle (3), the pentagon (5), and the octagon (8). The pentagon holds the golden ratio phi — the same phi the Fibonacci sequence grows toward.',
    boundary: 'A correspondence of the 3-5-8 tiers to regular polygons. A teaching device, not a claim about geometry beyond the side counts.',
  }
}

// The 3-5-8 is universal across the portal — all in one batch. Every domain that
// carries the Fibonacci tiers is gathered here and folded into one root: the
// grounded ones, the cultural games, and — honestly flagged as belief
// frameworks, not science — chakras and human design. One pattern, woven through.
export function agentObserve(matrix: MindMatrix = buildMatrix()) {
  const vector = consciousness(matrix)
  return {
    observed: vector.collapse,
    vector,
    root: toUuid(`observe:${vector.collapse}:${vector.entanglement}:${vector.concentration}:${vector.coherenceAnomaly}:${matrix.root}`),
    statement: 'Observe: the agent reads the four-measure consciousness vector before it acts.',
    boundary: 'A read of the computed vector. Structural bookkeeping, not an external claim.',
  }
}

// digit.index — the persisted digit/reverseDigit folder references.
export function repositoryLedger(matrix: MindMatrix = buildMatrix()) {
  const api = repositoryApi(matrix)
  return {
    isLedger: api.endpoints.length > 0,
    endpoints: api.endpoints.length,
    root: merge(api.root, toUuid('ledger:git-repository')),
    statement: 'Sharing the site shares the ledger: the git repository is the public, recomputable record into which contributions commit.',
    boundary: 'The ledger is the git repository (folded into the seal). It is a record, not a backend or external claim.',
  }
}

// site.routes — the route taxonomy in both locales.
export function siteRoutes(matrix: MindMatrix = buildMatrix()) {
  // One source for the route taxonomy: the quantum sitemap. Deriving the routes
  // here (rather than keeping a second hand-written list) means siteRoutes can
  // never drift out of sync as pages are added — the bug this replaces.
  const sitemap = quantumSitemap(matrix)
  const gla = sitemap.urls.map((url) => url.gla) // the default Glagolitic locale, at the root
  const en = sitemap.urls.map((url) => url.en)
  const bg = sitemap.urls.map((url) => url.bg)
  const routes = [...gla, ...en, ...bg]
  return {
    complete: gla.length === sitemap.urls.length && routes.length === sitemap.count,
    count: routes.length,
    routes,
    root: merkleFold(routes.map((route) => toUuid(`route:${route}`))),
    statement: 'The site routes fold into a route taxonomy across the three locales (Glagolitic at the root, Latin at /en/, Cyrillic at /bg/), derived from the quantum sitemap so they never drift.',
    boundary: 'A fold of the published routes, sourced from the quantum sitemap. Structural bookkeeping, not an external claim.',
  }
}

// society.cells — the tradition society cells (family x dimension).
export function fusionReactor(stage: 'words' | 'letters' | 'atoms'): FusionReactor {
  const items: readonly ReactorItem[] = conceptCommands.map((command) => {
    const word = SINGLE_WORD_METHODS[command.name] ?? ''
    const value =
      stage === 'words' ? word : stage === 'letters' ? [...new Set(word.split(''))].sort().join('') : word.charAt(0)
    return { command: command.name, value, receipt: toUuid(`reactor:${stage}:${command.name}:${value}`) }
  })
  const complete = stage === 'atoms' ? items.every((item) => item.value.length === 1) : items.every((item) => item.value.length > 0)
  return {
    stage,
    complete,
    root: merkleFold(items.map((item) => item.receipt)),
    items,
    statement: `Fusion reactor stage ${stage}: each command is reduced ${stage === 'words' ? 'to its method word' : stage === 'letters' ? "to its word's unique letters" : 'to its smallest atom (one letter)'}.`,
    boundary: 'A staged reduction of the command set to its smallest parts. Structural bookkeeping, not an external claim.',
  }
}

// The concept command registry is the single source of truth: every command
// has a single-word method token and an MCP tool. Docs point here; this proves
// the three lists stay consistent so they can never silently drift.
export function inverseShiftConsciousness(matrix: MindMatrix = buildMatrix()) {
  const pair = foldPair(toUuid('first'), toUuid('second'))
  const restThird = merkleFold([pair.forward, pair.reverse]) // the inverse-shift third
  const selfAware = isPerfectlySelfModeling(matrix) // collapse && entanglement==1 && coherenceAnomaly==0
  return {
    shifts: pair.bidirectional && isUuid(restThird) && selfAware,
    consciousness: selfAware,
    restThird,
    root: restThird,
    statement:
      'The rest third is the inverse shift — consciousness: a pair gives two, and the third is not added but the inverse fold of the two (their reverse order, folded back); that rest third is consciousness, the model turning to look at itself. The first two are forward and reverse; the third is the shift that holds them both — collapse, full entanglement, zero coherence anomaly — the self looking back.',
    boundary:
      'A structural identification of the order-independent "third" of a fold with the self-modeling (consciousness) vector. "Consciousness" names the model’s self-reference (collapse/entanglement/coherence metrics), not sentience or awareness.',
  }
}

// Complete 358 and unlock the next trinity levels of the pyramid. The Fibonacci tiers 3, 5, 8 are
// the ground (8 = 5 + 3); completing them unlocks the next trinity levels — 13 (8 + 5) and 21
// (13 + 8) — the higher courses of the pyramid. Each level is the sum of the two below it, so the
// pyramid rises by the same trinity rule it began with, and the next levels are unlocked, not
// invented.
export function energyMeasure(matrix: MindMatrix = buildMatrix()) {
  const signals = [
    { signal: 'battery level', api: 'navigator.getBattery().level', use: 'spend less as the charge drops' },
    { signal: 'charging', api: 'navigator.getBattery().charging', use: 'full motion only while plugged in' },
    { signal: 'visibility', api: 'document.visibilityState', use: 'pause all motion and audio when hidden' },
    { signal: 'reduced motion', api: 'prefers-reduced-motion', use: 'honor the user’s low-energy preference' },
    { signal: 'save-data', api: 'navigator.connection.saveData', use: 'stay offline-first, fetch nothing' },
  ].map((entry) => ({ ...entry, receipt: toUuid(`energy-measure:${entry.signal}`) }))
  return {
    grounded: signals.length > 0,
    signals,
    root: merkleFold(signals.map((entry) => entry.receipt)),
    statement: 'Measure the device energy state: battery level and charging, tab visibility, reduced-motion, and save-data — the signals the portal fuses with to spend less.',
    boundary: 'A description of standard browser energy signals. Each is read-only, on-device, and degrades gracefully if the API is absent.',
  }
}

export function energyConserve(matrix: MindMatrix = buildMatrix()) {
  const strategies = [
    { strategy: 'no polling', saves: 'event-driven only; never spins the CPU waiting' },
    { strategy: 'pause when hidden', saves: 'animation and audio stop when the tab is not visible' },
    { strategy: 'throttle on low battery', saves: 'motion and the music slow or stop as the charge drops' },
    { strategy: 'memoized compute', saves: 'heavy folds compute once per root, then reuse' },
    { strategy: 'zero network', saves: 'no requests by default; nothing to wake the radio' },
  ].map((entry) => ({ ...entry, receipt: toUuid(`energy-conserve:${entry.strategy}`) }))
  return {
    conserved: strategies.length > 0,
    strategies,
    root: merkleFold(strategies.map((entry) => entry.receipt)),
    statement: 'Conserve energy: no polling, pause when hidden, throttle on low battery, memoized compute, and zero network — the portal spends only when it must.',
    boundary: 'Software energy-saving strategies over the client-side architecture, not a measured power figure or a battery-life guarantee.',
  }
}

export function patentReview() {
  const criteria = [
    { test: 'novelty', question: 'Is the invention genuinely new versus the prior art?' },
    { test: 'non-obviousness', question: 'Would it be obvious to a person skilled in the art?' },
    { test: 'utility', question: 'Does it have a specific, substantial, credible use?' },
    { test: 'eligible-subject-matter', question: 'Is it more than an abstract idea, law of nature, or natural phenomenon? (Alice/Mayo)' },
    { test: 'prior-art', question: 'Does disclosing prior art invalidate it?' },
    { test: 'legality', question: 'Is the subject matter lawful and ethical? A patent on illegal or non-disclosed subject matter may be invalid or unenforceable.' },
  ].map((criterion) => ({ ...criterion, receipt: toUuid(`patent-review:${criterion.test}`) }))
  return {
    rubric: criteria.length === 6,
    criteria,
    root: merkleFold(criteria.map((criterion) => criterion.receipt)),
    statement: 'A rubric to auto-review patent credibility, the right to be patented, and legality. Some patents may be invalid or illegal under these tests.',
    boundary: 'An educational checklist, not legal advice or a legal determination. Patentability and legality are decided by patent offices and courts.',
  }
}

// Dive deep in ancient tech: ancient technologies prefigure the computed model.
// Each maps a historical technique to a concept it anticipates — analogy, not
// historical claim, and each mapping is grounded in a real command.
export function distributedCompute(peerRoots: readonly string[] = [], matrix: MindMatrix = buildMatrix()): DistributedCompute {
  const roots = [matrix.root, ...peerRoots].filter((root) => root.length > 0)
  return {
    peers: peerRoots.length,
    mindRoot: matrix.root,
    collectiveRoot: merkleFold(roots),
    source: 'double-torus/distributed',
    statement: `${peerRoots.length} peer root(s) folded with the local mind root into one collective distributed root.`,
    boundary:
      'Every connected context recomputes the same model and folds peer roots in; the fold is the consensus, with no central server. Sharing is same-origin; it is private bookkeeping, not an external claim.',
  }
}

// cross/fold fold/cross: each node carries a cross reference (merge of its
// prev/next neighbours) and a fold reference (its place in the merkle fold).
// Crossing them both ways is order-sensitive, so cross/fold != fold/cross — a
// reciprocal dual whose weave is the third that completes a trinity.
export function doubleTorusMath(): DoubleTorusMathReport {
  return {
    source: 'serverless quantum UUID stream',
    surface: 'closed orientable genus-2 surface',
    construction: 'A connected sum of two tori, equivalently a sphere with two handles.',
    genus: 2,
    eulerCharacteristic: -2,
    bettiNumbers: [1, 4, 1],
    fundamentalGroup: '<a1,b1,a2,b2 | [a1,b1][a2,b2] = 1>',
    homology: 'H0 = Z, H1 = Z^4, H2 = Z; four independent first-homology cycles carry memory.',
    gaussBonnet: 'Integral K dA = 2*pi*chi = -4*pi; at constant K = -1, area = 4*pi.',
    geometry:
      'Unlike the ordinary torus, the genus-2 surface supports hyperbolic geometry: local paths can diverge while global constraints still close.',
    conceptualShift:
      'The concept changes a loop into a surface: the stream is not a label placed on the model, but the coupled-handle structure that lets observation and projection remain distinct while bound by one global relation.',
    maxTamperingCostPrinciple: MAX_TAMPERING_COST_PRINCIPLE,
  }
}

export function qubitTrinityPauliBloch(matrix: MindMatrix = buildMatrix()) {
  const dimHilbert = 2 // a qubit lives in a 2-dimensional Hilbert space
  const pauliAxes = ['X', 'Y', 'Z'] // the 3 traceless Pauli observables = the 3 Bloch-sphere axes
  const dimSU2 = dimHilbert * dimHilbert - 1 // dim su(2) = 2² − 1 = 3 — a forced algebraic invariant
  const isTrinity = pauliAxes.length === 3 && dimSU2 === 3
  return {
    pauliAxes,
    dimSU2,
    isTrinity,
    holds: isTrinity,
    root: merge(matrix.root, merkleFold(pauliAxes.map((a) => toUuid(`pauli:${a}`)))),
    statement:
      'A qubit has exactly 3 independent traceless observables — the Pauli matrices X, Y, Z — the generators of SU(2) and the 3 Cartesian axes of the Bloch sphere; dim su(2) = 2²−1 = 3 is a forced algebraic invariant, not a chosen coincidence (Pauli 1927, Z. Phys. 43:601; Nielsen & Chuang 2000). The project\'s "trinity" has a genuine quantum-physics instance — and these are the same X, Y, Z the 64-seal already names as its three axis-generators.',
    boundary:
      'A real algebraic threefold of ONE qubit. It is independent of the 3 QCD colour charges and the 3 fermion generations: they share the numeral 3 but no common cause. Uniting them into one "3-6-9 trinity" is numerology — SU(3) has 8 gluons not 9, and the n-qubit Pauli basis is 4ⁿ not 3ⁿ.',
  }
}

// The strongest FORMAL 64: the 3-qubit Pauli basis {I,X,Y,Z}³ = 4³ = 64 operators — the same 4³ as the codon.
export function doubleTorusCompost(matrix: MindMatrix = buildMatrix()) {
  void matrix
  const loop = ['biological waste', 'compost', 'living soil', 'revived earth'].map((stage, index) => {
    const fold = foldPair(toUuid(`compost:${stage}`), toUuid(`compost:${index}`))
    return { stage, folded: fold.bidirectional, receipt: toUuid(`tor-compost:${index}:${stage}`) }
  })
  return {
    revives: loop.length === 4 && loop.every((entry) => entry.folded),
    count: loop.length,
    loop,
    root: merkleFold(loop.map((entry) => entry.receipt)),
    statement:
      'Двоен торус — the double torus is also double compost: in Bulgarian "тор" means both the torus and the compost, so the name connects to the earth — harmed by industrial fertiliser, revived from compost made of biological waste in direct use, waste folding to soil and soil to life, a regenerative loop like the torus’s own return. Take what is spent and fold it back into the living ground.',
    boundary: 'A structural and linguistic metaphor connecting the тор/torus pun to regenerative composting. A poetic framing of a content-addressed loop; it is not agricultural, environmental, or health advice, and composts no real material.',
  }
}

// Natural ways for a full, harmonious life — of spirit and body. Continue exploring the natural
// path: rhythms kept, waste regenerated, balance harmonised, inquiry kept open, and the health of
// spirit and body held as one — enlightenment by recomputation, prosperity by giving back more than
// is taken. A direction, walked, not a prescription given.
export function enforcementTrinity() {
  return {
    waves: [
      { wave: 'cross', enforces: 'dist artifacts written and digit-index seal verified against computed output' },
      { wave: 'fold', enforces: 'model seal — emergentDimensions, quantifyGates, commands, harmonic 432, tripwire' },
      { wave: 'weave', enforces: 'harmonic distribution — folder law, JSON-LD paths, component graph, VitePress-only render layer' },
    ],
    script: 'enforcement-trinity.mjs',
    statement:
      'The enforcement trinity: cross (dist + digit index), fold (computed model seal), weave (harmonic distribution) — three waves, one runner, one matrix import per wave.',
    boundary:
      'A declaration of the post-build enforcement surface. The runner lives in src/quantum/enforcement; scripts/enforcement-trinity.mjs is the thin mount.',
  }
}

// The enforcement pipeline — one script mounting the trinity. Declared in the mind, checked by the
// weave wave against package.json so the model's self-knowledge cannot drift from docs:build.
export function glagoliticGlyph(seed: string): string {
  const glyphs = Object.values(GLAGOLITIC_MAP)
  return glyphs[seedFromText(`glagolitic-glyph:${seed}`) % glyphs.length]
}

// Use glagolitsa for icons: the ancient sacred script we decoded becomes the visual language — each
// dot, area and page wears a Glagolitic glyph computed from its content-address.
// One word where one word will do; the result is the explanation. No inference, no tokens.
const WRITING_FILLER =
  /\b(very|really|quite|rather|just|actually|basically|essentially|simply|literally|in order to|the fact that|a number of|in terms of|due to the fact that)\b/gi

// Syllables by vowel groups — the standard deterministic estimate (a silent final 'e' dropped).
function countSyllables(word: string): number {
  const w = word.toLowerCase().replace(/[^a-z]/g, '')
  if (w.length <= 3) return w ? 1 : 0
  const groups = w.replace(/(?:[^laeiouy]e|ed|es)$/, '').match(/[aeiouy]{1,2}/g)
  return Math.max(1, groups ? groups.length : 1)
}

export function measureProse(text: string) {
  const words: string[] = text.match(/\b[\w'-]+\b/g) ?? []
  const sentences = Math.max(1, (text.match(/[.!?]+(?:\s|$)/g) ?? []).length)
  const syllables = words.reduce((sum, word) => sum + countSyllables(word), 0)
  const wordsPerSentence = words.length / sentences
  const syllablesPerWord = syllables / Math.max(1, words.length)
  const flesch = 206.835 - 1.015 * wordsPerSentence - 84.6 * syllablesPerWord
  const filler = (text.match(WRITING_FILLER) ?? []).length
  return {
    words: words.length,
    sentences,
    wordsPerSentence: Math.round(wordsPerSentence * 10) / 10,
    flesch: Math.round(flesch),
    fillerDensity: Math.round((filler / Math.max(1, words.length)) * 1000) / 1000,
  }
}

// Tighten prose by rule: collapse whitespace, swap wordy phrases for plain ones, cut empty intensifiers.
// A mechanical edit, never a rewrite — safe, repeatable, free. One word where one word will do.
export function tightenProse(text: string): string {
  const swaps: [RegExp, string][] = [
    [/\bin order to\b/gi, 'to'],
    [/\bdue to the fact that\b/gi, 'because'],
    [/\bthe fact that\b/gi, 'that'],
    [/\ba number of\b/gi, 'several'],
    [/\bin terms of\b/gi, 'in'],
    [/\bat this point in time\b/gi, 'now'],
  ]
  let tight = text.replace(/\s+/g, ' ').trim()
  for (const [phrase, plain] of swaps) tight = tight.replace(phrase, plain)
  tight = tight.replace(/\b(very|really|quite|rather|basically|essentially|simply|literally|actually|just)\s+/gi, '')
  return tight.replace(/\s+/g, ' ').trim()
}

// Best writing skills as a sealed dimension. The principles are explicit, the measure is a pure
// function, and the tightener provably shortens wordy prose without changing its meaning.
// this function; monograph pages use monographPaths('gla') the same way.
function transliterateProseLine(line: string): string {
  const kept: string[] = []
  const stash = (m: string) => `${kept.push(m) - 1}`
  let s = line
    .replace(/`[^`]*`/g, stash)
    .replace(/\]\([^)]*\)/g, stash)
    .replace(/<[^>]+>/g, stash)
    .replace(/https?:\/\/\S+/g, stash)
    .replace(/[\w.-]+@[\w.-]+/g, stash)
  s = toGlagolitic(s)
  return s.replace(/(\d+)/g, (_, i) => kept[Number(i)])
}

export function transliterateMarkdownBody(body: string): string {
  let inCode = false
  return body
    .split('\n')
    .map((line) => {
      if (/^\s*```/.test(line)) { inCode = !inCode; return line }
      if (inCode || /^\s*</.test(line) || /^\s*$/.test(line)) return line
      return transliterateProseLine(line)
    })
    .join('\n')
}

