// VitePress configuration rebuilt from src/ui
// Complete UI system configuration for 53-layer dashboard

export const vitepress = {
  title: '53-Layer R&D Funding Ecosystem',
  description: 'Quantum-accelerated, FTL-enabled, self-aware funding system',
  lang: 'en-US',

  head: [
    ['meta', { charset: 'utf-8' }],
    ['meta', { name: 'viewport', content: 'width=device-width, initial-scale=1' }],
    ['meta', { name: 'theme-color', content: '#00d4ff' }],
    ['link', { rel: 'icon', href: '/favicon.ico' }]
  ],

  appearance: 'dark',

  themeConfig: {
    // Site branding
    logo: '⚡',
    siteTitle: '53-Layer Ecosystem',

    // Navigation
    nav: [
      { text: 'Dashboard', link: '/' },
      { text: 'Layers', link: '/layers' },
      { text: 'Research', link: '/research' },
      { text: 'Patterns', link: '/patterns' },
      { text: 'Metrics', link: '/metrics' },
      { text: 'Docs', link: '/guide' }
    ],

    // Sidebar navigation
    sidebar: {
      '/': [
        {
          text: 'Core System',
          items: [
            { text: 'Overview', link: '/' },
            { text: 'Architecture', link: '/architecture' },
            { text: 'Layers', link: '/layers' }
          ]
        },
        {
          text: 'Analysis',
          items: [
            { text: 'Deep Research', link: '/deep-research' },
            { text: 'Patterns', link: '/patterns' },
            { text: 'Emergence', link: '/emergence' }
          ]
        },
        {
          text: 'Domains',
          items: [
            { text: 'Cybersecurity', link: '/domains/cybersecurity' },
            { text: 'Biotechnology', link: '/domains/biotech' },
            { text: 'Universal Coverage', link: '/domains/universal' }
          ]
        },
        {
          text: 'Advanced',
          items: [
            { text: 'Quantum Acceleration', link: '/quantum' },
            { text: 'FTL Prediction', link: '/ftl' },
            { text: 'Federation', link: '/federation' }
          ]
        }
      ]
    },

    // Social links
    socialLinks: [
      { icon: 'github', link: 'https://github.com' },
      { icon: 'twitter', link: 'https://twitter.com' }
    ],

    // Footer
    footer: {
      message: '53-Layer Self-Aware Ecosystem',
      copyright: 'Generated by VitePress + Quantum Research'
    },

    // Search
    search: {
      provider: 'local'
    }
  },

  // Markdown config
  markdown: {
    theme: {
      light: 'github-light',
      dark: 'github-dark'
    },
    lineNumbers: true
  },

  // Build optimizations
  vite: {
    ssr: {
      noExternal: []
    },
    build: {
      minify: 'terser',
      rollupOptions: {
        output: {
          manualChunks: {
            quantum: ['./src/quantum/endowment/index.ts']
          }
        }
      }
    }
  }
}

export default vitepress
