// ── The render barrel — the ONE browser-safe surface .vitepress consumes (dry-clean of the vitepress-thin-mount
// ratchet). Every .vitepress mount imports the folds it needs BY NAME from here; this file alone deep-imports src,
// so a trigram flatten only ever rewrites THIS barrel (the executor walks .vitepress), never the 53 consumers.
// Generated from the actual .vitepress import surface; re-exports resolve to the current fold locations.
/* eslint-disable */
export { STATUS_BADGE_KINDS, VORTEX_SEQUENCE, createAnimationEngine, humanBreath, pointerInteraction } from '../../src/0'
export type { StatusBadgeKind } from '../../src/0'
export { localeFromRoute, localePath } from '../../src/1/9'
export type { LocaleName } from '../../src/1/9'
export { CANONICAL_HOST, PHI, TAU } from '../../src/3/7'
export { geodesicDomeComputes, oneExponentialLaw } from '../../src/6/4'
export { livingTorus } from '../../src/fire/diamonds'
export { glagoliticHomeFromEnglish, onlyVitePressApi, selfDevelopment } from '../../src/fire/li'
export { AUDIO_DEFAULT_ENABLED, AUDIO_ENABLED_STORAGE_KEY, SCREENSAVER_IDLE_MS, SCREENSAVER_MOVIE_CHANNEL_IDS, allRealtimeComputationsVisibleInMovie, heroPhaseAt, movieAsMostEfficientScreensaver, plasmaBallComputes, plasmaMoviePalette, plasmaMovieStreams, plasmaWiredUuidStreams, realtimeComputationsMoviePaint, screensaverMovieComputes, screensaverMovieResearch } from '../../src/fire/plasma/ball'
export type { MovieScreensaverEfficiencyReceipt, PlasmaMoviePalette, PlasmaWiredStream, RealtimeComputationsMoviePaint, RealtimeComputeMovieChannel, ScreensaverTier } from '../../src/fire/plasma/ball'
export { foldQuestion } from '../../src/heaven/atoms'
export { SITE_LOCALES, componentPages } from '../../src/heaven/balance'
export type { JsonLdPageIdentity } from '../../src/heaven/balance'
export { buildMatrix, cardPage, cardPagePaths, cardPages, discoveryPage, discoveryPages, proveAllDeterministicCore, proveAllDeterministicCoreBeatAt, vitepressConfigComputesAll } from '../../src/heaven/compute'
export type { CardPage } from '../../src/heaven/compute'
export { MEEUS_J2000_CIVIL, MEEUS_J2000_JD, drawHumanDesignBodyGraph, humanDesignBodyGraphPanelComputes, humanDesignBodyGraphSvg, julianDayFromCivil } from '../../src/heaven/sky/astronomy'
export { siteNavigation, vitepressSidebar } from '../../src/learning'
export type { ComponentCrosslink } from '../../src/learning'
export { speechIntonation } from '../../src/media'
export { canonicalUrl, computedSeo, jsonLdTemplate, openGraphCardFromRoute, pageHreflangAlternates, platformOgLimitsMeasured, seoMetaDescription } from '../../src/mountain/og'
export { WATCH_MS_STORAGE_KEY, attunementTier, encodeWatchMsPersist, harmonizeField, parseWatchMsPersist } from '../../src/music'
export type { ObserverContext } from '../../src/music'
export { HERO_CYCLE_MS, QUANTUM_SENSOR_BINDING_CATALOG, backgroundSceneFromShared, cardFieldScroll, deviceSensorPerspectiveAt, deviceTouchPerspectiveAt, drawBackgroundMovie, drawBothEarthsMerkabaFrame, drawHeroMovieFrame, drawLivingTorusFrame, drawQuantumAppFrame, heroFieldCenterY, movieObservationReceipt, movieTextFromCopy, quantumSensorBindingCatalog, realtimeSubtitleAt, sharedHeroAt, subscribeHeroClock } from '../../src/quantum'
export type { BothEarthsMerkabaRotation, DeviceSensorSample, LivingTorusCoordinate, MoviePerspectiveBias, QuantumAppFrame, QuantumSensorKind, RealtimeSubtitleState, SharedHeroCopy, SharedHeroState } from '../../src/quantum'
export { SCIENCE_PAGE_CANON_SLOTS, SCIENCE_PAPER_SECTION_LABELS, componentProjectionFor, frontierNeighboursFor, pageComputedGapsAt, quantumAppForComponent, sciencePaperBodyFromCorpusSections, sciencePaperBodyFromDomainRow, slowProcessIsQuantumGap } from '../../src/quantum/apps'
export type { PageGapsKind, QuantumProjection, ScientificPageMeaning, ScientificPaperBody } from '../../src/quantum/apps'
export { homeMarkdown } from '../../src/quantum/dist'
export { localizeMonolingual, pickLocale, toGlagolitic } from '../../src/quantum/heaven/library'
export { A432_HUE, fixedConstantsProvedByTheorems, movieCanvasHex, movieCanvasRgba, observingMovieRevealsQuantumModel, quantumModelSnapshot, selfResearchTheorems } from '../../src/quantum/science'
export type { QuantumModelSnapshot, TheoremCandidate } from '../../src/quantum/science'
export { cursorReferralFundsAiNeeds, domainProofPageBySlug, domainProofPagePaths, domainProofPageRows } from '../../src/research'
export type { DomainProofCatalogRow } from '../../src/research'
export { backgroundMovieColors, decodedCardCrosslinksLabel, decodedCardFacetMark, decodedCardTextShadow, heroMovieChrome, immersiveMovieToggleLabel } from '../../src/thunder/movie/glass'
export type { HeroMovieChrome } from '../../src/thunder/movie/glass'
export { backgroundMovieColorVars, cardMovieColorVars, cardMoviePath, cardMovieSeed, heroInkColor } from '../../src/thunder/movie/movievars'
export { realtimeWiring } from '../../src/thunder/trading'
export { firstInCorpusProvenanceForHome, proofAnimations, specForContent, theoremGapScan, theoremNavigation, theoremProvenance } from '../../src/thunder/waves'
export type { ProofAnimationSpec } from '../../src/thunder/waves'
export { cosmosFrontiersDecoded } from '../../src/water/cosmos'
export { qrSvg } from '../../src/water/crypto'
export { ROSETTA_RAY_HUBS, rosettaRayHub } from '../../src/water/digit'
export { doubleTorusEarthExchangeComputes, doubleTorusEarthHingeComputesAll, fiatAndGoldFlowExplainedByDoubleEarthExchange, quantumGlobeAt } from '../../src/water/double/earth'
export { normalizeSslTestHostLabel, sslTestUiComplete } from '../../src/water/encryption'
export { collectiveContentAddressedMeshComputes, goldFusionComputes, thunderGoldGraphComputes, thunderGoldGraphFromPreciseGpsCoordinates, thunderGoldGraphResearch } from '../../src/wind/fusion'
export { catchAllRoutePaths, monographSliceFromRoute, vitepressAutomountPaths } from '../../src/wind/routes/automount'
export { CORPUS_GRID_PAGE_SIZE, computeUniversalPage, corpusCatchAllPaths, doubleTorusCorpusRouting, heroPreviewForRoute, openFrontierCardLinks, rayHubPart, rosettaBreadcrumbs, searchSectionsFor, theoremFigure, theoremPageBySlug, theoremPagePaths, theoremPageRows, theoremPapersLatestFirst, theoremTagIndex } from '../../src/wind/routes/corpus'
export type { FigRole, TheoremFigureData, TheoremPageRow, TheoremTagGroup, UniversalPage } from '../../src/wind/routes/corpus'
export { bulgarianHomeFromEnglish, githubPermalink, homeHero, localeNavLinks, localeSidebarKeys, revolutChannel, siteConfig, staticPages, vitepressDocsResearchImprovements, vitepressNativeDocsConfig } from '../../src/wind/site'
export type { LocalAnswer } from '../../src/types'
export { paperAbstractOmitsTitleEcho, rosettaIChingNavItems } from '../../src/ui'
