// Generated by Sparkle HDL
// Module: Alu.alu

module Alu_alu (
    input logic [2:0] _gen_op,
    input logic clk,
    input logic rst,
    output logic [63:0] out
);

    logic [15:0] _gen_x;
    logic [15:0] _gen_y;
    logic [15:0] _gen_z;
    logic _gen_isX;
    logic _gen_isY;
    logic _gen_isZ;
    logic _gen_isH;
    logic _gen_isS;
    logic _gen_isT;
    logic [15:0] _tmp_mux_then_7;
    logic [15:0] _tmp_mux_then_8;
    logic [31:0] _tmp_op_a_10;
    logic _tmp_sext_msb_11;
    logic [31:0] _tmp_op_b_13;
    logic _tmp_sext_msb_14;
    logic [15:0] _tmp_mux_then_30;
    logic [47:0] _tmp_reg_input_33;
    logic [47:0] _tmp_loop_body_35 = 48'h4000;


    assign _gen_x = _tmp_loop_body_35[47:32];

    assign _gen_y = _tmp_loop_body_35[31:16];

    assign _gen_z = _tmp_loop_body_35[15:0];

    assign _gen_isX = (_gen_op == 3'd1);

    assign _gen_isY = (_gen_op == 3'd2);

    assign _gen_isZ = (_gen_op == 3'd3);

    assign _gen_isH = (_gen_op == 3'd4);

    assign _gen_isS = (_gen_op == 3'd5);

    assign _gen_isT = (_gen_op == 3'd6);

    assign _tmp_mux_then_7 = -_gen_x;

    assign _tmp_mux_then_8 = -_gen_y;

    assign _tmp_sext_msb_11 = _tmp_loop_body_35[47:47];

    assign _tmp_op_a_10 = {16'(({_tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11, _tmp_sext_msb_11} & 16'd65535)), _gen_x};

    assign _tmp_sext_msb_14 = _tmp_loop_body_35[31:31];

    assign _tmp_op_b_13 = {16'(({_tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14, _tmp_sext_msb_14} & 16'd65535)), _gen_y};

    assign _tmp_mux_then_30 = -_gen_z;

    assign _tmp_reg_input_33 = {{16'(((_gen_isY ? _tmp_mux_then_7 : ((_gen_isZ ? _tmp_mux_then_7 : ((_gen_isH ? _gen_z : ((_gen_isS ? _tmp_mux_then_8 : ((_gen_isT ? 16'(($signed(((_tmp_op_a_10 - _tmp_op_b_13) * 32'd11585)) >>> $signed(32'd14))) : _gen_x) & 16'd65535)) & 16'd65535)) & 16'd65535)) & 16'd65535)) & 16'd65535)), 16'(((_gen_isX ? _tmp_mux_then_8 : ((_gen_isZ ? _tmp_mux_then_8 : ((_gen_isH ? _tmp_mux_then_8 : ((_gen_isS ? _gen_x : ((_gen_isT ? 16'(($signed(((_tmp_op_a_10 + _tmp_op_b_13) * 32'd11585)) >>> $signed(32'd14))) : _gen_y) & 16'd65535)) & 16'd65535)) & 16'd65535)) & 16'd65535)) & 16'd65535))}, 16'(((_gen_isX ? _tmp_mux_then_30 : ((_gen_isY ? _tmp_mux_then_30 : ((_gen_isH ? _gen_x : _gen_z) & 16'd65535)) & 16'd65535)) & 16'd65535))};

    always_ff @(posedge clk or posedge rst) begin
        if (rst)
            _tmp_loop_body_35 <= 48'd16384;
        else
            _tmp_loop_body_35 <= _tmp_reg_input_33;
    end

    assign out = {_tmp_loop_body_35, 16'(((_gen_z + 16'd16384) & 16'd65535))};

endmodule
