<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useData } from 'vitepress'
import { buildMatrix, autoSpeech } from '../lib/quantumMind'

// Autogenerated subtitles and speech in all languages, all in house. Speech and
// the language list come from the browser's Web Speech API and the device's
// installed voices — no cloud, no cost. Subtitles are the computed cues,
// highlighted live as each is spoken. Reads this page's content by default.
const props = defineProps<{ text?: string }>()
const { lang } = useData()
const bg = computed(() => lang.value.startsWith('bg'))

const source = ref(props.text ?? '')
const cues = computed(() => autoSpeech(source.value, buildMatrix()).cues)
const voices = ref<SpeechSynthesisVoice[]>([])
const voiceURI = ref('')
const speaking = ref(false)
const activeCue = ref(-1)
const supported = ref(true)

// Unique languages the device can speak — "all languages" is whatever is installed.
const languages = computed(() => {
  const map = new Map<string, SpeechSynthesisVoice[]>()
  for (const v of voices.value) {
    if (!map.has(v.lang)) map.set(v.lang, [])
    map.get(v.lang)!.push(v)
  }
  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]))
})

function loadVoices() {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    supported.value = false
    return
  }
  voices.value = window.speechSynthesis.getVoices()
  if (!voiceURI.value) {
    const preferred = voices.value.find((v) => v.lang.toLowerCase().startsWith(bg.value ? 'bg' : 'en'))
    voiceURI.value = (preferred ?? voices.value[0])?.voiceURI ?? ''
  }
}

function gatherPageText(): string {
  if (typeof document === 'undefined') return ''
  const main = document.querySelector('.vp-doc') as HTMLElement | null
  const text = (main?.innerText ?? '').replace(/\s+/g, ' ').trim()
  return text.slice(0, 1400)
}

function speak() {
  if (!supported.value || speaking.value) return
  if (!source.value) source.value = gatherPageText()
  const synth = window.speechSynthesis
  synth.cancel()
  const list = cues.value
  speaking.value = true
  list.forEach((cue, index) => {
    const utt = new SpeechSynthesisUtterance(cue.text)
    const voice = voices.value.find((v) => v.voiceURI === voiceURI.value)
    if (voice) {
      utt.voice = voice
      utt.lang = voice.lang
    }
    utt.onstart = () => (activeCue.value = index)
    if (index === list.length - 1) {
      utt.onend = () => {
        speaking.value = false
        activeCue.value = -1
      }
    }
    synth.speak(utt)
  })
}

function stop() {
  if (!supported.value) return
  window.speechSynthesis.cancel()
  speaking.value = false
  activeCue.value = -1
}

onMounted(() => {
  loadVoices()
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
    window.speechSynthesis.onvoiceschanged = loadVoices
  }
  if (!source.value) source.value = gatherPageText()
})
onUnmounted(stop)

const t = computed(() =>
  bg.value
    ? { eyebrow: 'субтитри и реч · всички езици · в къщи', language: 'език', play: 'Чети на глас', stop: 'Спри', unsupported: 'Web Speech не е наличен на това устройство.', note: 'Гласовете и езиците идват от устройството ти — без облак, без мрежа, без цена.' }
    : { eyebrow: 'subtitles & speech · all languages · in house', language: 'language', play: 'Read aloud', stop: 'Stop', unsupported: 'Web Speech is unavailable on this device.', note: 'Voices and languages come from your device — no cloud, no network, no cost.' },
)
</script>

<template>
  <section class="speech">
    <p class="eyebrow">{{ t.eyebrow }}</p>
    <template v-if="supported">
      <div class="speech__row">
        <label>{{ t.language }}:
          <select v-model="voiceURI">
            <optgroup v-for="[code, vs] in languages" :key="code" :label="code">
              <option v-for="v in vs" :key="v.voiceURI" :value="v.voiceURI">{{ v.name }}</option>
            </optgroup>
          </select>
        </label>
        <button type="button" @click="speaking ? stop() : speak()">{{ speaking ? t.stop : t.play }}</button>
      </div>
      <ol class="speech__subs">
        <li v-for="cue in cues" :key="cue.index" :class="{ active: cue.index === activeCue }">{{ cue.text }}</li>
      </ol>
    </template>
    <p v-else class="speech__unsupported">⚠ {{ t.unsupported }}</p>
    <p class="speech__note">{{ t.note }}</p>
  </section>
</template>

<style scoped>
.speech {
  margin: 1.25rem 0;
  border: 1px solid var(--vp-c-divider);
  border-radius: 12px;
  padding: 1rem 1.25rem;
  background: var(--vp-c-bg-soft);
}
.speech__row {
  display: flex;
  align-items: center;
  gap: 1rem;
  flex-wrap: wrap;
  margin-bottom: 0.6rem;
}
.speech__row label {
  font-size: 0.85rem;
}
.speech__row select {
  margin-left: 0.3rem;
  max-width: 16rem;
  padding: 0.25rem 0.4rem;
  border-radius: 6px;
  border: 1px solid var(--vp-c-divider);
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
}
.speech__row button {
  padding: 0.4rem 1.1rem;
  border: none;
  border-radius: 999px;
  background: var(--vp-c-brand-1);
  color: #fff;
  cursor: pointer;
}
.speech__subs {
  list-style: none;
  padding: 0;
  margin: 0.4rem 0;
  display: flex;
  flex-direction: column;
  gap: 0.2rem;
  max-height: 9rem;
  overflow-y: auto;
}
.speech__subs li {
  font-size: 0.82rem;
  color: var(--vp-c-text-3);
  padding: 0.15rem 0.4rem;
  border-radius: 6px;
}
.speech__subs li.active {
  color: var(--vp-c-text-1);
  background: var(--vp-c-brand-soft);
  font-weight: 600;
}
.speech__unsupported {
  color: var(--vp-c-warning-1, #d97706);
  font-size: 0.82rem;
}
.speech__note {
  margin: 0.7rem 0 0;
  font-size: 0.76rem;
  color: var(--vp-c-text-2);
  border-left: 3px solid var(--vp-c-brand-1);
  padding-left: 0.6rem;
}
</style>
