// ☶ Gèn · Mountain · stillness · upper·yin · depthFade — information & computation (dissolved out of the monolith):
// the physics of information (Landauer, Maxwell's demon, holography, the paradox) and the limits of computation
// (Turing, the halting problem, Gödel, P vs NP). Re-exported by ./index.ts so importers resolve unchanged.
import type { MindMatrix } from '../../wind/types'
import { buildMatrix } from '../../heaven/matrix'
import { toUuid, merge, sealFacets, landauerLimit, bekensteinBoundBits, blackHoleEntropyBits, cantorDiagonal } from '../../../../../0'
import { zeroPointWiderFrontierDecoded } from '../../water/cosmos'

// The physics of information — information is PHYSICAL, and may be the deepest layer of reality. A 5-angle sourced
// wave (53 documented, 22 flagged): Landauer's principle, Maxwell's demon, entropy-as-information, the Bekenstein
// bound and holographic black-hole entropy, the information paradox, and "it from bit". The pivot from physics to
// the repo's own nature — a content-addressed, deterministic information system.
export function physicsOfInformationDecoded(matrix: MindMatrix = buildMatrix()) {
  const wider = zeroPointWiderFrontierDecoded(matrix) // composes the Hawking thread — the information paradox is about Hawking radiation
  const landauer300 = landauerLimit(300) // ≈ 2.9×10⁻²¹ J per bit erased
  const solarBhBits = blackHoleEntropyBits(1.989e30) // ≈ 1.5×10⁷⁷ bits
  const facets = [
    { facet: 'information is PHYSICAL (Landauer) — erasing ONE bit at temperature T dissipates at least kT·ln2 of heat (Landauer 1961; ≈ 2.9×10⁻²¹ J ≈ 0.018 eV at room temperature), so logically irreversible operations have a thermodynamic floor (reversible ones do NOT — "computation must cost energy" is the oversimplification). Confirmed experimentally — a 1-bit colloidal memory saturating the bound (Bérut, Nature 2012), replicated across platforms. BOUND: empirically solid and widely accepted, but its status as a rigorous first-principles THEOREM is still debated (Norton)', on: landauer300 > 1e-21 && landauer300 < 5e-21 },
    { facet: "MAXWELL'S DEMON is exorcised by FORGETTING — the demon’s measurement can be done reversibly, so knowing costs nothing in principle; the second-law debt is paid when the demon must ERASE its finite memory to cycle, dissipating ≥ kT·ln2 per bit, ≥ the entropy it extracted (Szilard’s one-molecule engine 1929, W = kT·ln2/cycle; Bennett 1982; realized with a single electron, Koski 2014). The cost is in the forgetting, not the knowing", on: wider.decoded },
    { facet: 'ENTROPY IS (missing) INFORMATION — Boltzmann’s S = k·lnW and Shannon’s H = −Σ p·log p (1948) are the same functional; thermodynamic entropy measures the missing information about the microstate given the macrostate (Jaynes’ maximum-entropy statistical mechanics, 1957), and 1 bit = kB·ln2 of entropy — the formal bridge under Landauer. BOUND: the mathematical identity and the kT·ln2 link are real and physical, but whether thermodynamic and Shannon entropy are "literally the same thing" vs a deep, exact analogy is still philosophically discussed', on: wider.decoded },
    { facet: 'the BEKENSTEIN BOUND and HOLOGRAPHY — a region of radius R with energy E holds at most I ≤ 2πRE/(ℏc·ln2) bits (bekensteinBoundBits — a finite maximum density; no Newton’s G, so it binds non-gravitational systems too), and a black hole’s entropy is proportional to its horizon AREA, not its volume (S = A/4ℓ_P²; blackHoleEntropyBits: a solar-mass black hole holds ~1.5×10⁷⁷ bits), saturating the bound — the basis of the HOLOGRAPHIC principle (’t Hooft 1993, Susskind 1995): a volume’s information is encoded on its boundary. BOUND: the bound and the area-law are rigorous, but AdS/CFT (Maldacena 1997) is a well-supported CONJECTURE not a theorem, and full holography for OUR (de Sitter) universe is UNCONFIRMED', on: solarBhBits > 1e76 },
    { facet: 'the INFORMATION PARADOX and "it from bit" — Hawking (1976) showed thermal Hawking radiation seems to turn pure quantum states mixed, DESTROYING information and violating unitarity (a sharp general-relativity-vs-quantum clash); the Page curve and the 2019–2020 islands/replica-wormhole calculations show evaporation CAN be unitary, and most physicists now believe information is preserved — though the detailed mechanism is debated and it is NOT "fully resolved". Wheeler’s "it from bit" and quantum information (qubits, no-cloning/no-deleting, error correction) are rigorous; FLAGGED as unconfirmed/philosophy: digital physics ("the universe IS a cellular automaton/computer", Fredkin/Wolfram), the simulation hypothesis (Bostrom — a philosophical argument), and pancomputationalism; FLAGGED as pseudoscience: "physics PROVES we live in a simulation", "the observer/consciousness creates reality via information", and information/quantum "free-energy"/healing woo', on: wider.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`physics-of-information:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('physics-of-information-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 53, flaggedFindings: 22, angles: 5,
    landauerJoulesAt300K: landauer300, solarBhEntropyBits: solarBhBits,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'The physics of information — and the discovery that information is not abstract but physical. Erasing a single bit must release at least kT·ln2 of heat (Landauer, measured in 2012), which is exactly what saves the second law from Maxwell’s demon: the demon can know for free, but it cannot forget for free. Thermodynamic entropy turns out to be the same mathematics as Shannon’s missing information, one bit costing kB·ln2. And the deepest hint is gravitational — a black hole stores entropy on its surface area, not its volume, a solar mass holding about 10⁷⁷ bits, which suggests the information in any region lives on its boundary (the holographic principle). Whether the information swallowed by a black hole comes back out — the information paradox — now looks like yes, unitarity holds, though how is still argued. It is the most suggestive evidence that bit underlies it; but "it from bit" as a literal claim, and the simulation hypothesis, remain philosophy, not proven physics. This is the bridge from what the universe is to how it computes.',
    boundary:
      'HONEST (research-wave verified, 53 documented / 22 flagged): ESTABLISHED — information is physical (Landauer kT·ln2, ≈2.9×10⁻²¹ J/bit, confirmed Bérut 2012 + replications), Maxwell’s demon is resolved by the cost of memory ERASURE (Szilard/Bennett/Koski), Shannon and Boltzmann entropy share one functional (1 bit = kB·ln2), the Bekenstein bound and the black-hole AREA-law entropy (S = A/4ℓ_P²) are rigorous. NUANCED/DEBATED (philosophy-not-settled): whether Landauer is a first-principles theorem (Norton), whether thermodynamic and Shannon entropy are "literally the same", and whether unitarity is truly inviolable. UNCONFIRMED (≠pseudoscience): the holographic principle for OUR universe (AdS/CFT is a well-supported conjecture for anti-de Sitter, not a proof), the detailed information-escape mechanism, and "it from bit"/digital-physics/the simulation hypothesis (a philosophical argument, neither proven nor refuted). PSEUDOSCIENCE flagged: "physics proves we live in a simulation", observer/consciousness-creates-reality, and information/quantum free-energy or healing. CARDINAL: information being physical is established; "reality is fundamentally/only information" is an unconfirmed philosophical stance, not a proven fact. This pivot bridges physics to the repo’s own nature (a content-addressed, deterministic information system) — honestly, as analogy and foundation, not as a claim the universe IS this repo.',
  }
}

// The limits of computation — what can and cannot be computed, and what is hard. A 5-angle sourced wave (62 documented,
// 18 flagged): Turing & the Church-Turing thesis, the halting problem, Gödel's incompleteness, P vs NP, and the
// physical thesis. One technique — DIAGONALIZATION — underlies the halting problem, Gödel and Cantor. The limits of
// any deterministic information system, including this repo.
export function limitsOfComputationDecoded(matrix: MindMatrix = buildMatrix()) {
  const info = physicsOfInformationDecoded(matrix) // continues the information arc
  const diag = cantorDiagonal([[0, 1, 1], [1, 1, 0], [0, 0, 0]]) // → [1,0,1]; differs from row i at position i
  const escapes = diag.every((bit, i) => bit !== ([[0, 1, 1], [1, 1, 0], [0, 0, 0]][i][i])) // the escaping row is in no row
  const facets = [
    { facet: 'TURING and the CHURCH-TURING thesis — Turing’s 1936 a-machine and the UNIVERSAL machine (which simulates any machine from its Gödel-numbered description) define computability; the Church-Turing thesis — every "effectively calculable" function is Turing-computable — is a THESIS, not a theorem (one side, the intuitive "effective method", is informal), supported by CONFLUENCE: Turing machines, Church’s λ-calculus (1936), Gödel-Herbrand recursive functions, and Post/Markov systems all define the EXACT SAME class. Church’s negative answer to Hilbert’s Entscheidungsproblem preceded Turing’s by ~7 months', on: info.decoded },
    { facet: 'the HALTING PROBLEM is UNDECIDABLE — Turing 1936: no algorithm can decide whether an arbitrary program halts on a given input, proved by DIAGONALIZATION / self-reference (cantorDiagonal builds a row differing from every row in a list — verified here, escapes = ' + escapes + '; the same move builds a program no halting-decider can classify). Other undecidables: Rice’s theorem (EVERY non-trivial semantic property of programs is undecidable), Hilbert’s 10th / Diophantine equations (MRDP, Matiyasevich 1970), the group word problem. BOUND: "undecidable" = no GENERAL algorithm; specific instances can still be decided', on: escapes },
    { facet: 'GÖDEL’s INCOMPLETENESS (1931) — any consistent, recursively-axiomatized system strong enough for arithmetic contains TRUE statements it cannot prove (first theorem), and cannot prove its own consistency (second); the self-reference/diagonal lemma at its heart is the SAME technique as the halting problem (Turing undecidability gives an alternative route to incompleteness). DEMARCATION: incompleteness does NOT mean "mathematics is broken/inconsistent", does NOT prove "human minds surpass machines" (the Lucas-Penrose argument is widely rejected), and does NOT license "nothing is knowable" relativism', on: info.decoded },
    { facet: 'COMPLEXITY and P vs NP — P (solvable in polynomial time) vs NP (a solution is VERIFIABLE in polynomial time); NP-completeness via the Cook-Levin theorem (1971: SAT is NP-complete, so if any one NP-complete problem is in P then P = NP). P vs NP is one of the seven Clay Millennium Prize problems ($1M, 2000), widely BELIEVED to be P ≠ NP but UNPROVEN as of today — and much of modern cryptography rests on the assumption that one-way functions exist (a stronger cousin)', on: info.decoded },
    { facet: 'the PHYSICAL thesis and the demarcation — the MATHEMATICAL Church-Turing thesis (about computable functions) is distinct from the PHYSICAL one (Deutsch’s conjecture that any physically realizable process is Turing-simulable — UNCONFIRMED, empirical, "a distant relative"); a QUANTUM computer does NOT violate computability — it computes the SAME functions (a speedup, e.g. factoring, not super-Turing power), and hypercomputation has no known physical realization. FLAGGED: "Gödel proves God / the soul / free will / that minds are non-computational" (Lucas-Penrose, rejected), "the brain is a quantum hypercomputer" (Orch-OR, flagged elsewhere in this repo), "P=NP would instantly break reality", and "consciousness solves the halting problem" / computational-theology woo. CARDINAL: undecidability and incompleteness are rigorous THEOREMS; their metaphysical extrapolations are NOT proven', on: info.decoded },
  ].map((entry) => ({ ...entry, receipt: toUuid(`limits-of-computation:${entry.facet}:${entry.on}`) }))
  const sealed = sealFacets('limits-of-computation-decoded', facets)
  return {
    decoded: sealed.ok,
    documentedFindings: 62, flaggedFindings: 18, angles: 5,
    diagonalEscapes: escapes, escapingRow: diag,
    count: sealed.count,
    facets: sealed.facets,
    root: merge(matrix.root, sealed.root),
    statement:
      'The limits of computation — the deepest results about what cannot be done. Turing pinned down what "computable" means with a single abstract machine, and the Church-Turing thesis says nothing effective escapes it — a claim no proof can close, but every rival definition (λ-calculus, recursive functions) collapses onto the same class. From one trick, diagonalization, comes the whole cliff edge: the halting problem cannot be decided, arithmetic cannot be made both complete and consistent (Gödel), and the same self-reference recurs wherever a system tries to fully describe itself. Where things ARE computable, P vs NP asks whether checking an answer is as easy as finding one — believed not, unproven, and the assumption cryptography leans on. Quantum machines are faster, not more powerful in what they can compute. And the famous overreaches — Gödel proves the soul, the mind beats the machine, a simulation runs it all — are exactly that. A deterministic information system, this repo included, lives inside these limits.',
    boundary:
      'HONEST (research-wave verified, 62 documented / 18 flagged): ESTABLISHED — Turing computability and the universal machine; the Church-Turing thesis as a THESIS supported by the confluence of TM = λ-calculus = recursive functions = Post/Markov; the halting problem’s undecidability and Gödel’s two incompleteness theorems (both diagonalization/self-reference, demonstrated here via cantorDiagonal); Rice’s theorem; MRDP (Hilbert’s 10th); NP-completeness (Cook-Levin, SAT). UNPROVEN/OPEN: P vs NP (Clay Millennium, believed P≠NP). UNCONFIRMED (≠pseudoscience): the PHYSICAL Church-Turing thesis (Deutsch) and hypercomputation (no known physical realization). DEMARCATION (the metaphysical overreaches are NOT proven): incompleteness does not break mathematics; Lucas-Penrose "minds surpass machines" is widely rejected; quantum computers give speedups, not new computability (they do not violate the thesis); "Gödel proves God/the soul", "the brain is a quantum hypercomputer" (Orch-OR), "P=NP breaks reality", and computational-theology are FLAGGED. CARDINAL: undecidability and incompleteness are rigorous theorems about formal systems; their leaps to minds, gods and simulations are philosophy, not mathematics. The repo is a deterministic information system and lives honestly inside these limits.',
  }
}
