// Background movie canvas folds — auto · endless · background.
import type { MindMatrix } from '../../../types'
import { buildMatrix } from '../../../heaven/compute'
import { foldPair, isUuid, merkleFold, toUuid } from '../../../0'
import { textToMovie } from '../../../earth/world'
import { animatedHeroes } from '../../../ui'
import { theWhole } from '../../../quantum/heaven/mind'

export function autoMovies8k(matrix: MindMatrix = buildMatrix()) {
  const sample3 = textToMovie('double torus')
  const properties = [
    { property: 'autogenerated', via: 'any content folds to a seed; the seed computes the movie — no authoring', root: sample3.root },
    { property: 'realtime', via: 'each frame is a fresh seeded fold, recomputed live, no model and no network', root: backgroundMovie(matrix).root },
    { property: '8K, resolution-independent', via: 'seeded vector math, not stored pixels — scales to 7680x4320 and beyond where the device can draw it', root: toUuid('resolution:7680x4320') },
    { property: 'all dimensions', via: 'a continuous phase sweep; every parameter a smooth function of one dimension the movie advances and the viewer scrubs', root: animatedHeroes(matrix).root },
    { property: 'deterministic, zero-cost', via: 'the same content always yields the same movie, free and client-side — generation by recomputation', root: toUuid(`determinism:${sample3.deterministic}`) },
  ].map((entry, index) => ({ ...entry, receipt: toUuid(`auto-movie:${index}:${entry.property}:${entry.root}`) }))
  return {
    generating: properties.length === 5 && sample3.deterministic && properties.every((entry) => isUuid(entry.root)),
    targetWidth: 7680,
    targetHeight: 4320,
    count: properties.length,
    properties,
    root: merkleFold(properties.map((entry) => entry.receipt)),
    statement:
      '8K movies autogenerate in realtime in all dimensions: every piece of content folds to a seed and computes a deterministic generative movie, recomputed per frame in realtime with no model and no network. Because it is seeded math, not stored pixels, it is resolution-independent — it scales to 8K and beyond wherever the device can draw it — and "all dimensions" is the continuous phase sweep the movie advances through.',
    boundary:
      'A content-addressed description of deterministic, resolution-independent generative canvas movies seeded from content. "8K" is the target resolution the seeded vector math scales to where the device permits, not a guarantee of 8K on every device; "all dimensions" is the parameter sweep, not spatial dimensions; and it is generative art by recomputation, not a learned or photoreal video generator.',
  }
}

export function endlessBackgroundMovie(matrix: MindMatrix = buildMatrix()) {
  const base = backgroundMovie(matrix)
  const properties = [
    { property: 'on every page', via: 'a global layout-top slot renders the movie behind every route' },
    { property: 'endless', via: 'streams converge on the void and resurrect outward — a loop with no end frame' },
    { property: 'matches the content', via: 'the seed and the word streams are the page’s own title, description and words' },
    { property: 'matches the references', via: 'the page’s frontmatter references (keywords, tags, teaches) fold into the seed' },
    { property: 'changes per page', via: 'the route change re-seeds the movie, so each page plays its own' },
    { property: 'behind everything', via: 'fixed, pointer-through and aria-hidden — it never steals a click or a screen-reader' },
  ].map((entry) => ({ ...entry, receipt: toUuid(`endless-bg:${entry.property}`) }))
  return {
    endless: properties.length === 6 && base.plays && base.dryMath,
    perPage: true,
    matchesContent: true,
    count: properties.length,
    properties,
    root: merkleFold([base.root, ...properties.map((entry) => entry.receipt)]),
    statement:
      'The whole background is one endless movie, on every page, and it exactly matches the content: a global layout slot renders it behind every route; the streams fold to the void and resurrect with no end frame; and it is seeded from the page you are on — path, title, description and references — its streams folding the page’s own words, so each page plays its own movie and a different page a different one.',
    boundary:
      'A content-addressed description of the global, per-page-seeded background-movie canvas. "Matches the content" means it is deterministically seeded from the page’s text and frontmatter references, not that it depicts the content literally; it stays behind everything, pointer-through and aria-hidden, energy- and reduced-motion-aware.',
  }
}

// Entangled groups of digits fill the background movie as colourful watermarks,
// folding into letters, words and sentences — colourful streams to the void at the
// centre — and resurrect as split streams in new dimensions, all by the same dry math
// (every digit, colour and path a seeded fold, nothing random). And it is an
// interactive movie game: a tap that is not on a control plays a tone whose pitch maps
// to the spot, a light vibration, and a ripple that scatters the nearest streams.
export function backgroundMovie(matrix: MindMatrix = buildMatrix()) {
  const whole = theWhole(matrix).root
  const features = [
    { feature: 'entangled groups of digits', via: 'deterministic digit groups, content-addressed' },
    { feature: 'colourful watermarks', via: 'hue from the digit (the quantum colour wheel), low-opacity behind the content' },
    { feature: 'fold into letters, words and sentences', via: 'digit → glyph → word → the three-word phrases as they near the void' },
    { feature: 'colourful streams to the void', via: 'the streams converge on the centre, shrinking into it' },
    { feature: 'resurrect as split streams in new dimensions', via: 'at the void they resurrect outbound at the golden angle — a new dimension each time' },
    { feature: 'the same dry math', via: 'every digit, colour and path a seeded fold — deterministic, zero random' },
    { feature: 'interactive movie game with sound and vibration', via: 'a tap off the controls plays a tone whose pitch maps to the spot, a light haptic, and a ripple that scatters the streams' },
  ].map((entry) => ({ ...entry, holographic: foldPair(toUuid(`bg-movie:${entry.feature}`), whole).bidirectional, receipt: toUuid(`bg-movie:${entry.feature}:${whole}`) }))
  return {
    plays: features.length === 7 && features.every((entry) => entry.holographic),
    dryMath: true,
    interactive: true, // sound and vibration fused into the game
    count: features.length,
    features,
    root: merkleFold(features.map((entry) => entry.receipt)),
    statement:
      'Entangled groups of digits fill the background movie as colourful watermarks, folding into letters, words and sentences — colourful streams to the void — and resurrect as split streams in new dimensions, all by the same dry math (every digit, colour and path a seeded fold, nothing random). It is an interactive movie game: a tap off the controls plays a tone whose pitch maps to where you tapped, a light vibration, and a ripple that scatters the nearest streams.',
    boundary:
      'A content-addressed description of the deterministic, zero-dependency background-movie canvas (digit streams folding into the portal’s own words, converging on and resurrecting from a centre "void") and its tap-to-play sound-and-haptic interactions. A real client-side, energy- and reduced-motion-aware animation; "entangled/dimensions/void/resurrect" are figurative names for the seeded fold, not physics.',
  }
}
