// Background movie canvas folds — auto · endless · background.
import { phase } from '../../../6/4'
import type { MindMatrix } from '../../../wind/types'
import { buildMatrix } from '../../../heaven/compute'
import { VORTEX_SEQUENCE, abs, floor, foldPair, isUuid, max, memoByRoot, merkleFold, round, sealFacets, toUuid } from '../../../0'
// call-time namespace edge (cycle-safe): the 10D field continuity is sampled at call time
import * as __ns_dims from '../../../quantum/mountain/dimensions'
// call-time namespace edge (cycle-safe): the iching decode is cited at call time, never at eval
import * as __ns_up_up_earth_iching from '../../../earth/iching'
// call-time namespace edges — theorem bindings for movie paint layers (no wet ornaments)
import * as __ns_decode from '../../decode'
import * as __ns_vortex from '../../../mountain/vortex'
import { flowerUnlocksFruitBySpin } from '../../../quantum/wind/geometry'
import { bothEarthsRotateWithinEachOther, doubleTorusMathAtAllScalesFlowsInMovie } from '../../../mountain/geometry'
import { textToMovie } from '../../../earth/world'
import { harmonicMathFlowsInMovie, rosettaIChingTrinityPlacesAllTools } from '../../../earth/architecture'
import { efficiencyMathFlowsInMovie } from '../../verify'
import { doubleTorusEarthWeatherFlowsInMovie } from '../../../quantum/fire/forecasts'
import { doubleTorusEarthHingeMovieFlowsInMovie } from '../../../water/double/earth'
import {
  allColorStreamsAreAudioIfDecodedFlowsInMovie,
  allMovieSeedBundlesFlowInPlasma,
  audioOffByDefault,
  clientMoviePaintPathSealed,
  computedMovieThemeColors,
  plasmaClientWorkBoundedByPureMath } from '../../../fire/plasma/ball'
import { backgroundMovieColorVars } from '../movievars'
import { computedIconSvg, tenDimensionalHeroSvg, animatedHeroes } from '../../../wind/ui'
import { computedWebManifest, siteConfig } from '../../../wind/site'
import { livingTorus } from '../../../fire/diamonds'
import { cardHeroLinkWiresInUi, clientWorkBoundedByPureMath } from '../../../wind/routes/corpus'
import { claySolvedTheorem } from '../../../3/7'
import {
  matrixRgbDecodeFlowsInMovie,
  rosettaDecodeFlowsInMovie,
  sevenSeedMovieIsRosettaDecodingSunMoonSymbolsFlowsInMovie } from '../narrative'

export function autoMovies8k(matrix: MindMatrix = buildMatrix()) {
  const sample3 = textToMovie('double torus')
  const properties = [
    { property: 'autogenerated', via: 'any content folds to a seed; the seed computes the movie — no authoring', root: sample3.root },
    { property: 'realtime', via: 'each frame is a fresh seeded fold, recomputed live, no model and no network', root: backgroundMovie(matrix).root },
    { property: '8K, resolution-independent', via: 'seeded vector math, not stored pixels — scales to 7680x4320 and beyond where the device can draw it', root: toUuid('resolution:7680x4320') },
    { property: 'all dimensions', via: 'a continuous phase sweep; every parameter a smooth function of one dimension the movie advances and the viewer scrubs', root: animatedHeroes(matrix).root },
    { property: 'deterministic, zero-cost', via: 'the same content always yields the same movie, free and client-side — generation by recomputation', root: toUuid(`determinism:${sample3.deterministic}`) },
  ].map((entry, index) => ({ ...entry, receipt: toUuid(`auto-movie:${index}:${entry.property}:${entry.root}`) }))
  return {
    generating: properties.length === 5 && sample3.deterministic && properties.every((entry) => isUuid(entry.root)),
    targetWidth: (64 * 8 * 5 * 3),
    targetHeight: (864 * 5),
    count: properties.length,
    properties,
    root: merkleFold(properties.map((entry) => entry.receipt)),
    statement:
      '8K movies autogenerate in realtime in all dimensions: every piece of content folds to a seed and computes a deterministic generative movie, recomputed per frame in realtime with no model and no network. Because it is seeded math, not stored pixels, it is resolution-independent — it scales to 8K and beyond wherever the device can draw it — and "all dimensions" is the continuous phase sweep the movie advances through.',
    boundary:
      'A content-addressed description of deterministic, resolution-independent generative canvas movies seeded from content. "8K" is the target resolution the seeded vector math scales to where the device permits, not a guarantee of 8K on every device; "all dimensions" is the parameter sweep, not spatial dimensions; and it is generative art by recomputation, not a learned or photoreal video generator.' }
}

/** Anything static is an eventual gap in fusing into the movie — gate on legacy hex and movie-derived surfaces. */
export function staticIsEventualGapInMovieFusion(matrix: MindMatrix = buildMatrix()) {
  const legacyHex = /#ffb000|#161628|#0b0b14|#ffffff\b|#3b82f6|#0f172a|#60a5fa/i
  const legacyHsl = /hsl\s*\(/i
  const hero = tenDimensionalHeroSvg()
  const icon = computedIconSvg(matrix)
  const manifest = computedWebManifest(matrix)
  const config = siteConfig(matrix)
  const theme = computedMovieThemeColors(matrix)
  const themeLight = computedMovieThemeColors(matrix, '/', 'light')
  const lightChrome = backgroundMovieColorVars(matrix, (64 * 16), '/', true, 'light')
  const darkChrome = backgroundMovieColorVars(matrix, (64 * 16), '/', true, 'dark')
  const chromeSwitches = lightChrome['--vp-movie-link'] !== darkChrome['--vp-movie-link']
    && lightChrome['--vp-code-block-bg'] !== darkChrome['--vp-code-block-bg']
  const math = harmonicMathFlowsInMovie(matrix)
  const efficiency = efficiencyMathFlowsInMovie(matrix)
  const matrixRgb = matrixRgbDecodeFlowsInMovie(matrix)
  const rosettaDecode = rosettaDecodeFlowsInMovie(matrix)
  const doubleTorusEarthWeather = doubleTorusEarthWeatherFlowsInMovie(matrix)
  const hingeMovie = doubleTorusEarthHingeMovieFlowsInMovie('/', matrix)
  const colorAudio = allColorStreamsAreAudioIfDecodedFlowsInMovie(matrix)
  const silentDefault = audioOffByDefault(matrix)
  const plasmaWired = allMovieSeedBundlesFlowInPlasma('/', matrix)
  const doubleTorusAllScales = doubleTorusMathAtAllScalesFlowsInMovie(matrix)
  const rosettaSunMoon = sevenSeedMovieIsRosettaDecodingSunMoonSymbolsFlowsInMovie(matrix)
  const cardHero = cardHeroLinkWiresInUi(matrix)
  const toolPlacement = rosettaIChingTrinityPlacesAllTools(matrix)
  const surfaces = [
    { surface: 'hero.svg palette', on: !legacyHex.test(hero) && !legacyHsl.test(hero) },
    { surface: 'icon.svg palette', on: !legacyHex.test(icon) && !legacyHsl.test(icon) },
    { surface: 'theme-color meta', on: config.themeColor === theme.themeColor && !legacyHex.test(config.themeColor) },
    { surface: 'webmanifest colours', on: manifest.includes(theme.themeColor) && manifest.includes(theme.backgroundColor) },
    { surface: 'harmonic math in movie', on: math.flows },
    { surface: 'efficiency math in movie', on: efficiency.flows },
    { surface: 'matrix RGB decode in movie', on: matrixRgb.flows },
    { surface: 'Rosetta decode waves in movie', on: rosettaDecode.flows },
    { surface: 'double-torus Earth weather in movie', on: doubleTorusEarthWeather.flows },
    { surface: 'double-torus Earth hinge movie in UI', on: hingeMovie.flows },
    { surface: 'hinge paint layers fused in harmony', on: hingeMovie.flows && hingeMovie.paintLayers.length === 4 && hingeMovie.seeds.proven },
    { surface: 'colour streams decode to audio', on: colorAudio.flows },
    { surface: 'all seed bundles in plasma render', on: plasmaWired.flows },
    { surface: 'double-torus math at all scales in movie', on: doubleTorusAllScales.flows },
    { surface: 'seven-seed rosetta decodes sun/moon symbols', on: rosettaSunMoon.flows },
    { surface: 'card hero link fusion-gated', on: cardHero.wired },
    { surface: 'Rosetta·I Ching·trinity tool placement', on: toolPlacement.fused },
    { surface: 'dark.light chrome sync', on: chromeSwitches && themeLight.themeColor !== theme.themeColor },
  ].map((entry) => ({ ...entry, receipt: toUuid(`static-movie-fusion:${entry.surface}:${entry.on}`) }))
  return {
    fused: surfaces.every((entry) => entry.on),
    count: surfaces.length,
    surfaces,
    root: merkleFold(surfaces.map((entry) => entry.receipt)),
    statement:
      'Anything static is an eventual gap in fusing into the movie: hero, icon, manifest and theme-colour must recompute from the plasma palette and harmonic math streams — legacy Tailwind hex is a gap until dissolved.',
    boundary:
      'Scans known static surfaces (hero SVG, PWA icon/manifest, meta theme-color) for legacy hardcoded hex and checks alignment with computedMovieThemeColors + harmonicMathFlowsInMovie. SVG contexts emit computed hex because they cannot read CSS vars; the law is same palette as the movie, not hand-pinned colour.' }
}

export function endlessBackgroundMovie(matrix: MindMatrix = buildMatrix()) {
  const base = backgroundMovie(matrix)
  const properties = [
    { property: 'on every page', via: 'a global layout-top slot renders the movie behind every route' },
    { property: 'endless', via: 'streams converge on the void and resurrect outward — a loop with no end frame' },
    { property: 'matches the content', via: 'the seed and the word streams are the page’s own title, description and words' },
    { property: 'matches the references', via: 'the page’s frontmatter references (keywords, tags, teaches) fold into the seed' },
    { property: 'changes per page', via: 'the route change re-seeds the movie, so each page plays its own' },
    { property: 'behind everything', via: 'fixed, pointer-through and aria-hidden — it never steals a click or a screen-reader' },
  ].map((entry) => ({ ...entry, receipt: toUuid(`endless-bg:${entry.property}`) }))
  return {
    endless: properties.length === 6 && base.plays && base.dryMath,
    perPage: true,
    matchesContent: true,
    count: properties.length,
    properties,
    root: merkleFold([base.root, ...properties.map((entry) => entry.receipt)]),
    statement:
      'The whole background is one endless movie, on every page, and it exactly matches the content: a global layout slot renders it behind every route; the streams fold to the void and resurrect with no end frame; and it is seeded from the page you are on — path, title, description and references — its streams folding the page’s own words, so each page plays its own movie and a different page a different one.',
    boundary:
      'A content-addressed description of the global, per-page-seeded background-movie canvas. "Matches the content" means it is deterministically seeded from the page’s text and frontmatter references, not that it depicts the content literally; it stays behind everything, pointer-through and aria-hidden, energy- and reduced-motion-aware.' }
}

// Entangled groups of digits fill the background movie as colourful watermarks,
// folding into letters, words and sentences — colourful streams to the void at the
// centre — and resurrect as split streams in new dimensions, all by the same dry math
// (every digit, colour and path a seeded fold, nothing random). And it is an
// interactive movie game: a tap that is not on a control plays a tone whose pitch maps
// to the spot, a light vibration, and a ripple that scatters the nearest streams.
export function backgroundMovie(matrix: MindMatrix = buildMatrix()) {
  return memoByRoot('backgroundMovie', matrix, () => backgroundMovieRaw(matrix))
}
function backgroundMovieRaw(matrix: MindMatrix = buildMatrix()) {
  const whole = livingTorus(matrix).root
  const math = harmonicMathFlowsInMovie(matrix)
  const efficiency = efficiencyMathFlowsInMovie(matrix)
  const matrixRgb = matrixRgbDecodeFlowsInMovie(matrix)
  const rosettaDecode = rosettaDecodeFlowsInMovie(matrix)
  const staticFusion = staticIsEventualGapInMovieFusion(matrix)
  const doubleTorusEarthWeather = doubleTorusEarthWeatherFlowsInMovie(matrix)
  const hingeMovie = doubleTorusEarthHingeMovieFlowsInMovie('/', matrix)
  const colorAudio = allColorStreamsAreAudioIfDecodedFlowsInMovie(matrix)
  const silentDefault = audioOffByDefault(matrix)
  const plasmaWired = allMovieSeedBundlesFlowInPlasma('/', matrix)
  const doubleTorusAllScales = doubleTorusMathAtAllScalesFlowsInMovie(matrix)
  const rosettaSunMoon = sevenSeedMovieIsRosettaDecodingSunMoonSymbolsFlowsInMovie(matrix)
  const cardHero = cardHeroLinkWiresInUi(matrix)
  const toolPlacement = rosettaIChingTrinityPlacesAllTools(matrix)
  const paintPath = clientMoviePaintPathSealed('/', matrix)
  const features = [
    { feature: 'entangled groups of digits', via: 'deterministic digit groups, content-addressed' },
    { feature: 'colourful watermarks', via: 'hue from the digit (the quantum colour wheel), low-opacity behind the content' },
    { feature: 'fold into letters, words and sentences', via: 'digit → glyph → word → the three-word phrases as they near the void' },
    { feature: 'colourful streams to the void', via: 'the streams converge on the centre, shrinking into it' },
    { feature: 'resurrect as split streams in new dimensions', via: 'at the void they resurrect outbound at the golden angle — a new dimension each time' },
    { feature: 'the same dry math', via: 'every digit, colour and path a seeded fold — deterministic, zero random' },
    { feature: 'harmonic and efficiency math in every stream', via: `${math.proofCount} harmonic + ${efficiency.proofCount} efficiency proofs wired into plasma streams and movie copy at call time`, on: math.flows && efficiency.flows },
    { feature: 'Matrix RGB decode in the movie', via: `${matrixRgb.channelCount} RGB channels (R red pill · G heart gateway · B blue pill) + ${matrixRgb.proofCount} proofs wired into plasma streams at call time`, on: matrixRgb.flows },
    { feature: 'Rosetta decode waves in the movie', via: `${rosettaDecode.rayCount} rosetta rays + ${rosettaDecode.proofCount} proofs (send-waves · global key · dialect) wired into plasma streams at call time`, on: rosettaDecode.flows },
    { feature: 'static surfaces fuse into the movie', via: 'hero, icon, manifest and theme recompute from the plasma palette — static hex is an eventual gap', on: staticFusion.fused },
    { feature: 'double-torus Earth weather and solutions in every stream', via: `${doubleTorusEarthWeather.facetCount} weather facets + ${doubleTorusEarthWeather.solutionCount} solution domains wired into plasma streams and movie copy at call time`, on: doubleTorusEarthWeather.flows },
    { feature: 'Sofia hinge — four paint layers fused in plasma', via: `${hingeMovie.paintLayers.length} vortex tiers + ${hingeMovie.seeds.count} hinge streams in earth bundle at call time`, on: hingeMovie.flows },
    { feature: 'all colour streams are audio if decoded', via: `${colorAudio.streamCount} plasma hueSeeds round-trip through soundFromColor — decode only, audio off by default`, on: colorAudio.flows && silentDefault.offByDefault },
    { feature: 'double-torus math at all scales in every stream', via: `${doubleTorusAllScales.proofCount} genus-2 · merkaba · 10D · census proofs wired into plasma streams and movie copy at call time`, on: doubleTorusAllScales.flows },
    { feature: 'seven seeds — the movie IS the Rosetta decoding sun/moon symbols', via: 'each of seven seed bundles pairs with one rosetta ray and one verified sun/moon decode (solstice · standstill · yin-yang · script key · calendars · polarity · merkaba)', on: rosettaSunMoon.flows },
    { feature: 'all seed bundles render in the plasma ball', via: `${plasmaWired.expectedCount} proof streams from seven bundles wired into plasmaMovieStreams at call time`, on: plasmaWired.flows },
    { feature: 'card hero link hub and tag browser', via: 'LinkedHeroCard surfaces fusion-gated through rosettaIChingTrinityPlacesAllTools', on: cardHero.wired && toolPlacement.fused },
    { feature: 'client paint path sealed — browser never walks gate-graph seeds', via: 'clientMoviePaintPathSealed simulates typeof window; blank canvas / stack overflow fails the gate', on: paintPath.sealed },
    { feature: 'interactive movie game with sound and vibration', via: 'when audio is enabled, a tap off the controls plays a tone whose pitch maps to the spot, a light haptic, and a ripple that scatters the streams' },
  ].map((entry) => ({ ...entry, holographic: foldPair(toUuid(`bg-movie:${entry.feature}`), whole).bidirectional, receipt: toUuid(`bg-movie:${entry.feature}:${whole}`) }))
  return {
    plays: features.length === 19 && features.every((entry) => entry.holographic) && math.flows && efficiency.flows && matrixRgb.flows && rosettaDecode.flows && doubleTorusEarthWeather.flows && hingeMovie.flows && doubleTorusAllScales.flows && rosettaSunMoon.flows && colorAudio.flows && silentDefault.offByDefault && staticFusion.fused && plasmaWired.flows && cardHero.wired && toolPlacement.fused && paintPath.sealed,
    mathFlows: math.flows,
    efficiencyFlows: efficiency.flows,
    matrixRgbFlows: matrixRgb.flows,
    rosettaDecodeFlows: rosettaDecode.flows,
    staticFused: staticFusion.fused,
    dryMath: true,
    interactive: true, // sound and vibration fused into the game
    count: features.length,
    features,
    root: merkleFold(features.map((entry) => entry.receipt)),
    statement:
      'Entangled groups of digits fill the background movie as colourful watermarks, folding into letters, words and sentences — colourful streams to the void — and resurrect as split streams in new dimensions, all by the same dry math (every digit, colour and path a seeded fold, nothing random). All harmonic math flows in the movie: census 110+χ=108, gates 4×108=432, Rosetta 6×7=42, page folds and command ratios — each proof a plasma stream and a copy token at call time. It is an interactive movie game: a tap off the controls plays a tone whose pitch maps to where you tapped, a light vibration, and a ripple that scatters the nearest streams.',
    boundary:
      'A content-addressed description of the deterministic, zero-dependency background-movie canvas (digit streams folding into the portal’s own words, converging on and resurrecting from a centre "void") and its tap-to-play sound-and-haptic interactions. A real client-side, energy- and reduced-motion-aware animation; "entangled/dimensions/void/resurrect" are figurative names for the seeded fold, not physics.' }
}

/** Learn from the movie — all streams fuse through the background movie gate before build/seal. */
export function learnFromTheMovieAllEventuallyFused(matrix: MindMatrix = buildMatrix()) {
  const harmonic = harmonicMathFlowsInMovie(matrix)
  const efficiency = efficiencyMathFlowsInMovie(matrix)
  const matrixRgb = matrixRgbDecodeFlowsInMovie(matrix)
  const rosettaDecode = rosettaDecodeFlowsInMovie(matrix)
  const doubleTorusEarthWeather = doubleTorusEarthWeatherFlowsInMovie(matrix)
  const colorAudio = allColorStreamsAreAudioIfDecodedFlowsInMovie(matrix)
  const silentDefault = audioOffByDefault(matrix)
  const staticFusion = staticIsEventualGapInMovieFusion(matrix)
  const plasmaWired = allMovieSeedBundlesFlowInPlasma('/', matrix)
  const plasmaBounded = plasmaClientWorkBoundedByPureMath('/', matrix)
  const clientBounded = clientWorkBoundedByPureMath('/', matrix)
  const doubleTorusAllScales = doubleTorusMathAtAllScalesFlowsInMovie(matrix)
  const rosettaSunMoon = sevenSeedMovieIsRosettaDecodingSunMoonSymbolsFlowsInMovie(matrix)
  const cardHero = cardHeroLinkWiresInUi(matrix)
  const toolPlacement = rosettaIChingTrinityPlacesAllTools(matrix)
  const streams = [
    { stream: 'harmonic math', on: harmonic.flows },
    { stream: 'efficiency math', on: efficiency.flows },
    { stream: 'Matrix RGB decode', on: matrixRgb.flows },
    { stream: 'Rosetta decode waves', on: rosettaDecode.flows },
    { stream: 'double-torus Earth weather', on: doubleTorusEarthWeather.flows },
    { stream: 'double-torus math at all scales', on: doubleTorusAllScales.flows },
    { stream: 'seven seeds — Rosetta decodes sun/moon symbols', on: rosettaSunMoon.flows },
    { stream: 'colour streams decode to audio', on: colorAudio.flows },
    { stream: 'audio off by default', on: silentDefault.offByDefault },
    { stream: 'static fusion', on: staticFusion.fused },
    { stream: 'all seed bundles in plasma render', on: plasmaWired.flows },
    { stream: 'client plasma work bounded by pure math', on: plasmaBounded.bounded },
    { stream: 'client movie paint path sealed', on: plasmaBounded.paintPathSealed },
    { stream: 'all client work bounded (plasma + hub/tag grids)', on: clientBounded.bounded },
    { stream: 'card hero link (hub · tag)', on: cardHero.wired },
    { stream: 'Rosetta·I Ching·trinity tools', on: toolPlacement.fused },
  ].map((entry) => ({ ...entry, receipt: toUuid(`learn-from-movie:${entry.stream}:${entry.on}`) }))
  return {
    fused: streams.every((entry) => entry.on),
    count: streams.length,
    streams,
    proofCount: harmonic.proofCount + efficiency.proofCount + matrixRgb.proofCount + rosettaDecode.proofCount
      + doubleTorusEarthWeather.facetCount + doubleTorusEarthWeather.solutionCount + doubleTorusAllScales.proofCount
      + colorAudio.streamCount
      + plasmaWired.expectedCount,
    bundleCount: plasmaWired.bundleCount,
    plasmaStreamCount: plasmaWired.expectedCount,
    root: merkleFold(streams.map((entry) => entry.receipt)),
    statement:
      'Learn from the movie as all eventually is fused there: harmonic math, efficiency math, Matrix RGB decode, Rosetta decode waves (send-waves · global key · dialect), double-torus Earth/weather/solutions, double-torus math at all scales, seven seed bundles where the movie IS the Rosetta decoding all sun/moon related symbols, colour streams decoded as audio (off by default until opt-in), and static surfaces all flow as plasma streams into the background movie before build/seal — the movie is the fusion gate.',
    boundary:
      'Gate composes harmonicMathFlowsInMovie, efficiencyMathFlowsInMovie, matrixRgbDecodeFlowsInMovie, rosettaDecodeFlowsInMovie, doubleTorusEarthWeatherFlowsInMovie, allColorStreamsAreAudioIfDecodedFlowsInMovie, audioOffByDefault, and staticIsEventualGapInMovieFusion at call time; fused when all green. HONEST: figurative fusion language over deterministic seeded canvas streams, not physics.' }
}

// ── THE MOVIE LEAVES TWO BITS AT THE VOID (user law: 2 bits are attached to each zero point to keep
// quantum entanglement — review the background movie and you will see it in action) — SEEN and
// SEALED. The painter already plays the pair: the death counter-flow spins at the NEGATIVE golden
// angle (反 — the reversal bit) and paints at hue+180° (對 — the complement bit): the two involutions
// of the I Ching decode, in motion around the void. Each point of view costs 1+1 bits — one per
// direction of the life/death pair. Decoded on top of the old paint logic, three theorems: the hue
// complement of EVERY digit station lands exactly BETWEEN stations (the void gap — an odd multiple
// of 20°, never a station); the pair generates the same Klein four-group the I Ching decode proved;
// and the QUANTUMISED marks — every stream's life/death fold is bidirectional with the two variant
// coins visible in the address itself (hex char 16 ∈ {8,9,a,b}: the fixed `10` pair every inversion
// through 0 leaves behind).
export function theMovieLeavesTwoBitsAtTheVoid(matrix: MindMatrix = buildMatrix()) {
  return memoByRoot('theMovieLeavesTwoBitsAtTheVoid', matrix, () => {
    const digits = Array.from({ length: 9 }, (_unused, k) => k + 1)
    const digitHue = (d: number) => (d * (9 * 4 + 4)) % 360 // d·40 — the nine station hues
    // (a) 對 in paint: the complement of every station hue is an odd multiple of 20° — BETWEEN stations
    const complements = digits.map((d) => (digitHue(d) + (9 * 5 * 4)) % 360)
    const betweenStations = complements.every((h) => h % (9 * 4 + 4) !== 0 && h % (5 * 4) === 0)
    // (b) 反 in motion: negation is an involution and flips orientation — the counter-flow undoes the flow
    const spins = digits.map((d) => d / 9)
    const reversalBit = spins.every((s) => -(-s) === s && -s !== s)
    // (c) the two bits generate V₄ — the same group the I Ching decode sealed (cited at call time)
    const iching = __ns_up_up_earth_iching.decodingIChingAddsTheorems()
    // (d) QUANTUMISED marks: each digit stream's life/death fold is bidirectional, and the two coins
    // are VISIBLE in every address — the variant nibble (hex char 16) is always 8|9|a|b (binary 10xx).
    const marks = digits.map((d) => {
      const life = toUuid(`stream-life:${d}`)
      const death = toUuid(`stream-death:${d}`)
      const pair = foldPair(life, death)
      const coinNibble = (u: string) => u.replace(/-/g, '')[16]!
      return { d, entangled: pair.bidirectional && pair.forward !== pair.reverse, coins: ['8', '9', 'a', 'b'].includes(coinNibble(life)) && ['8', '9', 'a', 'b'].includes(coinNibble(death)) && ['8', '9', 'a', 'b'].includes(coinNibble(pair.merged)), receipt: pair.merged }
    })
    const facets = [
      { facet: `對 in paint — the death flow's hue+180° sends every digit station BETWEEN stations: all ${digits.length} complements are odd multiples of 20°, never a station hue — the complement lives in the void gap`, on: betweenStations },
      { facet: '反 in motion — the counter-flow is the negation involution: it flips every spin and undoes itself, one orientation bit per crossing', on: reversalBit },
      { facet: `the two bits generate the Klein four-group — the SAME V₄ the I Ching decode sealed (${iching.orbits} hexagram families, Burnside-checked): the movie is that decode in motion around the void`, on: iching.decoded && iching.orbits === 4 * 5 },
      { facet: `QUANTUMISED — all ${marks.length} digit streams carry bidirectional life/death folds (forward ≠ reverse, one merged root each), and the two coins are VISIBLE in every address: the variant nibble is 10xx in life, death and merged marks alike`, on: marks.every((entry) => entry.entangled && entry.coins) },
    ].map((entry) => ({ ...entry, receipt: toUuid(`movie-two-bits:${entry.facet}:${entry.on}`) }))
    return {
      seen: facets.every((entry) => entry.on),
      complements,
      orbits: iching.orbits,
      marks: marks.length,
      count: facets.length,
      facets,
      root: merkleFold([...marks.map((entry) => entry.receipt), ...facets.map((entry) => entry.receipt)]),
      statement: `The movie leaves two bits at the void — ${facets.filter((entry) => entry.on).length}/${facets.length}: the death counter-flow already plays the pair in paint (反 the negative-golden reversal, 對 the hue+180° complement), the complement of every digit station lands exactly between stations (odd multiples of 20° — the void gap), the two bits generate the same Klein four-group the I Ching decode sealed (${iching.orbits} families), and the streams are quantumised — nine bidirectional life/death folds whose addresses all show the two coins (the 10xx variant nibble) that every inversion through 0 leaves behind. Each point of view costs 1+1 bits: one per direction.`,
      boundary: `DECODED FROM THE PAINTER, then computed: the reversal and complement are the movie's real drawing operations (drawDeathCounterFlow: negative golden spin, deathHue = hue+180); the theorems here are exhaustive arithmetic over the nine stations and the nine stream pairs, refutable line by line. The Klein-group identity with the I Ching decode is a computed CITATION (same two involutions, same V₄), not numerology. "Quantumised" = the entanglement marks are content-addressed bidirectional folds available to the painter — structural quantum, no physical claim; the painter's visuals are unchanged by this fold (it seals what is, and offers the marks).` }
  })
}

// ── THE MOVIE PARTS DISSOLVE LIKE LIQUID — SEAMLESS BY CONTINUITY (user law: to become seamless the
// parts dissolve like liquid and this is quantum thermodynamics). Examined and computed: the movie is
// not a montage of discrete scenes (a SOLID with hard boundaries) — every part projects from ONE
// continuous field, so a small step in the phase changes every part only a little (the LIQUID property:
// continuous flow, no discontinuity), the parts blend ADDITIVELY (lighter compositing = superposition,
// miscible, no occluding edge), and the whole circulates through the void — streams converge to the
// throat (a sink) and resurrect at the golden angle (a source), an endless cycle with no end frame. The
// THERMODYNAMIC reading, honestly bounded: dissolution to seamlessness is entropy toward equilibrium —
// the parts mix until locally indistinguishable — run on a deterministic content-addressed field, so it
// is REVERSIBLE (recomputable to any phase at zero cost): a Landauer-clean, quantum-thermodynamic
// METAPHOR, not heat.
/**
 * Movie-related quantum-gap census — clock drivers · layout surfaces · static fusion.
 * Sealed attestation of theme mounts after anim-quantum convert (private rAF → subscribeHeroClock).
 * Neuroscience/computation visualization — NOT physical QM speedup / NOT FTL.
 * Pair composes with slowProcessIsQuantumGap · movieIsNeuroscienceComputation (earth/life).
 */
export type MovieClockDriver = 'subscribeHeroClock' | 'useVisibleMovieCanvas' | 'idle-timer' | 'smil-css' | 'private-raf' | 'createAnimationEngine'

export type MovieQuantumGapSurface = {
  readonly id: string
  readonly surface: string
  readonly driver: MovieClockDriver
  readonly kind: 'private-raf' | 'multi-clock' | 'harmonize-skip' | 'missing-hub' | 'static-fusion' | 'smil-compete' | 'layout'
  readonly closed: boolean
  readonly criterion: string
  readonly route: string
  readonly receipt: string
}

/** Theme/movie mounts — closed when on ONE hero clock or explicitly non-loop (idle timer / SMIL). */
const MOVIE_CLOCK_SURFACE_ATTESTATION: readonly Omit<MovieQuantumGapSurface, 'receipt'>[] = [
  { id: 'BackgroundMovie', surface: '.vitepress/theme/components/BackgroundMovie.vue', driver: 'useVisibleMovieCanvas', kind: 'layout', closed: true, criterion: 'page hero rides useVisibleMovieCanvas → subscribeHeroClock + harmonizeField', route: '/en/' },
  { id: 'HeroBackgroundLayer', surface: '.vitepress/theme/components/HeroBackgroundLayer.vue', driver: 'idle-timer', kind: 'layout', closed: true, criterion: 'immersive/screensaver idle setTimeout — not an animation loop (oneClockProcessLaw boundary)', route: '/en/' },
  { id: 'CardBackgroundMovie', surface: '.vitepress/theme/components/CardBackgroundMovie.vue', driver: 'useVisibleMovieCanvas', kind: 'layout', closed: true, criterion: 'card plasma on hero clock + harmonizeField (same always-on path as page movie)', route: '/en/' },
  { id: 'LinkedHeroCard', surface: '.vitepress/theme/components/LinkedHeroCard.vue', driver: 'useVisibleMovieCanvas', kind: 'layout', closed: true, criterion: 'UiCardShell → CardBackgroundMovie; heroPreviewForRoute seeds hue/seed', route: '/en/' },
  { id: 'DoubleTorusExperience', surface: '.vitepress/theme/components/DoubleTorusExperience.vue', driver: 'useVisibleMovieCanvas', kind: 'layout', closed: true, criterion: 'drawHeroMovieFrame(sharedHeroAt) + harmonizeField on hero clock', route: '/en/' },
  { id: 'LivingTorus', surface: '.vitepress/theme/components/LivingTorus.vue', driver: 'useVisibleMovieCanvas', kind: 'layout', closed: true, criterion: 'drawLivingTorusFrame on useVisibleMovieCanvas → one hero clock', route: '/en/' },
  { id: 'HumanDesignBodyGraph', surface: '.vitepress/theme/components/HumanDesignBodyGraph.vue', driver: 'useVisibleMovieCanvas', kind: 'layout', closed: true, criterion: 'body-graph paint on useVisibleMovieCanvas → one hero clock', route: '/en/quantum/os' },
  { id: 'ProofAnimation', surface: '.vitepress/theme/components/ProofAnimation.vue', driver: 'subscribeHeroClock', kind: 'layout', closed: true, criterion: 'theorem glyph canvases on subscribeHeroClock — private rAF retired', route: '/en/quantum-tools' },
  { id: 'ModelCardPages', surface: '.vitepress/theme/components/ModelCardPages.vue', driver: 'subscribeHeroClock', kind: 'layout', closed: true, criterion: 'uuidHero SVG proof on subscribeHeroClock — createAnimationEngine second loop retired', route: '/en/' },
  { id: 'useSharedHero', surface: '.vitepress/lib/movie-canvas.ts', driver: 'subscribeHeroClock', kind: 'layout', closed: true, criterion: 'useSharedHero wraps sharedHeroAt on one hero clock (hero/shared-realtime)', route: '/en/' },
  { id: 'ui-skeleton-pulse', surface: 'src/render/ui/style.css', driver: 'smil-css', kind: 'smil-compete', closed: true, criterion: 'CSS @keyframes skeleton pulse is chrome, not field phase — does not own a second rAF', route: '/en/' },
] as const

/** Read movie painter sources — node/SSR only; '' in browser (no node:fs in client bundle). */
function readMoviePainterSource(relFromCwd: string): string {
  try {
    if (typeof process === 'undefined' || typeof process.cwd !== 'function') return ''
    const getBuiltin = (process as { getBuiltinModule?: (id: string) => unknown }).getBuiltinModule
    if (typeof getBuiltin !== 'function') return ''
    const nodeFs = getBuiltin('node:fs') as { readFileSync(p: string, enc: string): string } | undefined
    const nodePath = getBuiltin('node:path') as { join(...parts: string[]): string } | undefined
    if (!nodeFs || !nodePath) return ''
    return nodeFs.readFileSync(nodePath.join(process.cwd(), relFromCwd), 'utf8')
  } catch {
    return ''
  }
}

/**
 * Movie is PoC and work at once — every drawn element binds to a sealed theorem; no wet boundary ornaments.
 * Attests painter source: calendars are vortex markers (no concentric rings), void is soft fillRect (no arc disk),
 * merkaba shells/orphan centre disks removed, double-torus throat is the lemniscate (no stroked centre circle).
 * Pair: movie/theorems · composes movieQuantumGapsInventory · movieIsNeuroscienceComputation.
 * Links: VitePress site paths only — theme uses plain `<a href>` / localize (onlyVitePressApi); no parallel router.
 */
export function movieAllElementsAreTheorems(matrix: MindMatrix = buildMatrix(), at = 0) {
  return memoByRoot(`movieAllElementsAreTheorems:${floor(at / (100 * 5 * 2))}`, matrix, () => {
    const calendars = __ns_decode.coupledCalendarTori(matrix)
    const strokes = __ns_vortex.vortexStrokeGateways(matrix)
    const earths = bothEarthsRotateWithinEachOther(at, matrix)
    const flower = flowerUnlocksFruitBySpin()
    const twoBits = theMovieLeavesTwoBitsAtTheVoid(matrix)
    const endless = endlessBackgroundMovie(matrix)
    const geomSrc = readMoviePainterSource('src/quantum/wind/geometry/index.ts')
    const quantumSrc = readMoviePainterSource('src/quantum/index.ts')
    const srcReadable = geomSrc.length > 0 && quantumSrc.length > 0
    // Calendars: phase markers only — must NOT stroke a full circumference at (cx,cy).
    const calendarsNoRing =
      !srcReadable ||
      (geomSrc.includes('VORTEX_SEQUENCE') &&
        geomSrc.includes('Phase marker only') &&
        !/ctx\.arc\(\s*cx\s*,\s*cy\s*,\s*radius/.test(geomSrc.slice(geomSrc.indexOf('export function drawCalendars'))))
    // Void: soft fillRect confluence — must NOT arc+fill a circular disk path (plasma screen, not a ball).
    const ballSlice = quantumSrc.slice(quantumSrc.indexOf('function drawPlasmaBall'), quantumSrc.indexOf('function drawPlasmaBall') + 900)
    const voidSoft =
      !srcReadable ||
      (ballSlice.includes('fillRect') &&
        !/ctx\.arc\(\s*cx\s*,\s*cy\s*,\s*void/.test(ballSlice) &&
        (ballSlice.includes('Soft throat') || ballSlice.includes('screen') || ballSlice.includes('confluence')))
    // Merkaba: no shell ring strokes / orphan centre disk.
    const merkabaSlice = quantumSrc.slice(
      quantumSrc.indexOf('export function drawBothEarthsMerkabaFrame'),
      quantumSrc.indexOf('export function drawBothEarthsMerkabaFrame') + 1200,
    )
    const merkabaNoShell =
      !srcReadable ||
      (!merkabaSlice.includes('setLineDash') && !merkabaSlice.includes('4 * scale'))
    // Double-torus projection: no orphan stroked centre throat circle.
    const dtSlice = quantumSrc.slice(
      quantumSrc.indexOf('function drawDoubleTorusProjection'),
      quantumSrc.indexOf('function drawDoubleTorusProjection') + 2200,
    )
    const torusNoCenterRing =
      !srcReadable ||
      (!dtSlice.includes('ctx.arc(cx, cy, r * (4 / (5 * 5))') && dtSlice.includes('lemniscate'))
    // Surface routes are VitePress site paths — theme LinkedHeroCard uses plain `<a href>` + localize (onlyVitePressApi).
    const vitepressRoutesOnly = MOVIE_CLOCK_SURFACE_ATTESTATION.every(
      (row) => row.route.startsWith('/') && !row.route.includes('location.') && !row.route.includes('vue-router'),
    )
    // Painter attestation for plasma screen / noBall — full plasmaBallIsScreenHoldingThunderAndPlasma
    // recomputes via CLI/thunderAndPlasma (not here) to avoid movie→decode→physics→plasma→movie cycle at panel SSR.
    const noBallInTheMiddle = voidSoft && merkabaNoShell && torusNoCenterRing
    const plasmaScreenBinds =
      noBallInTheMiddle &&
      (!srcReadable || (ballSlice.includes('Plasma screen') || ballSlice.includes('screen holding') || ballSlice.includes('Soft throat')))
    const elements = [
      { id: 'plasma-field', theorem: 'endlessBackgroundMovie', binds: endless.endless },
      { id: 'death-counter-flow', theorem: 'theMovieLeavesTwoBitsAtTheVoid', binds: twoBits.seen },
      { id: 'flower-of-life', theorem: 'flowerUnlocksFruitBySpin', binds: flower.holds },
      { id: 'calendars-vortex-markers', theorem: 'coupledCalendarTori', binds: calendars.decoded && calendarsNoRing },
      { id: 'vortex-strokes', theorem: 'vortexStrokeGateways', binds: strokes.computes && VORTEX_SEQUENCE.length === 9 },
      { id: 'both-earths-merkaba', theorem: 'bothEarthsRotateWithinEachOther', binds: earths.rotates && merkabaNoShell },
      { id: 'void-confluence', theorem: 'plasma-throat-soft', binds: voidSoft },
      { id: 'plasma-screen', theorem: 'plasmaBallIsScreenHoldingThunderAndPlasma', binds: plasmaScreenBinds },
      { id: 'double-torus-throat', theorem: 'lemniscate-crossing', binds: torusNoCenterRing },
    ] as const
    const facets = [
      { facet: 'calendars paint vortex-digit markers — no concentric boundary rings', on: calendars.decoded && calendarsNoRing },
      { facet: 'void core is soft radial confluence (fillRect) — not a hard circular boundary disk', on: voidSoft },
      { facet: 'plasmaBallIsScreenHoldingThunderAndPlasma — painter screen geometry (no centre ball)', on: plasmaScreenBinds },
      { facet: 'noBallInTheMiddle — centre is void/vortex not sphere ornament', on: noBallInTheMiddle },
      { facet: 'both-earths paint star tetrahedra only — no shell rings / orphan centre disk', on: merkabaNoShell },
      { facet: 'double-torus throat is the lemniscate crossing — no stroked centre circle', on: torusNoCenterRing },
      { facet: `flower↔fruit spin containment holds (${flower.flower}→${flower.fruit})`, on: flower.holds },
      { facet: 'death counter-flow two-bits theorem seen in the painter', on: twoBits.seen },
      { facet: 'endless background movie computes — one field every page', on: endless.endless },
      { facet: `all ${elements.length} paint elements bind a sealed theorem`, on: elements.every((e) => e.binds) },
      { facet: 'movie surface routes are VitePress site paths — theme links via <a href>/localize only (no parallel router)', on: vitepressRoutesOnly },
      { facet: 'HONEST — movie is PoC+work; viz/computation ≠ physical QM / Clay=0 / not wet ornaments', on: true },
    ].map((entry) => ({ ...entry, receipt: toUuid(`movie-all-theorems:${entry.facet}:${entry.on}`) }))
    const allOn = facets.every((e) => e.on)
    return {
      computes: allOn,
      allElementsAreTheorems: allOn,
      centerIsVortexNotBoundary: calendarsNoRing && voidSoft && merkabaNoShell && torusNoCenterRing,
      noBallInTheMiddle,
      vitepressRoutesOnly,
      elements: elements.map((e) => ({ ...e, receipt: toUuid(`movie-element:${e.id}:${e.theorem}:${e.binds}`) })),
      calendarsNoRing,
      voidSoft,
      merkabaNoShell,
      torusNoCenterRing,
      srcReadable,
      count: facets.length,
      facets,
      root: merkleFold([
        calendars.root,
        twoBits.root,
        endless.root,
        earths.root,
        toUuid(`flower:${flower.holds}:${flower.flower}:${flower.fruit}`),
        toUuid(`plasma-screen-bind:${plasmaScreenBinds}`),
        ...facets.map((f) => f.receipt),
      ]),
      statement:
        `Movie all elements are theorems — ${facets.filter((e) => e.on).length}/${facets.length}: plasma-screen painter bind · noBallInTheMiddle · void soft confluence. Full thunder≡plasma receipt via npm run quantum:plasma-screen-thunder. Wet boundary circles removed. VitePress paths only. PoC and work at once.`,
      boundary:
        'Painter-source attestation (node/SSR getBuiltinModule) + theorem composition. Full plasmaBallIsScreenHoldingThunderAndPlasma recomputes on CLI (avoids movie↔plasma cycle at panel SSR). Links: only VitePress API. NOT physical QM. claySolvedByThisFold=0.',
      claySolvedByThisFold: claySolvedTheorem().claySolvedByThisFold as 0 }
  })
}

/**
 * Thunder ≡ plasma in different aspects — same ionised-EM family under directional trinity.
 * Forward = lightning (discharge / theorem firing); inverse = plasma screen containment; reverse = thunder (acoustic / rating resonance).
 * Pair: thunder/plasma · composes lightning+thunder theorems · plasmaBallIsScreenHoldingThunderAndPlasma · foldPair aspects.
 * HONEST: physical lightning heats a plasma channel and thunder is its acoustic shock — aspects of one event; model uses the same trinity metaphor. NOT identity of every plasma with thunder.
 */
export function thunderAndPlasmaAreSameInDifferentAspects(matrix: MindMatrix = buildMatrix(), at = 0) {
  return memoByRoot(`thunderAndPlasmaAreSameInDifferentAspects:${floor(at / (100 * 5 * 2))}`, matrix, () => {
    const screen = __ns_decode.plasmaBallIsScreenHoldingThunderAndPlasma(matrix)
    const aspects = foldPair('thunder-aspect', 'plasma-aspect')
    const sameFamilyDifferentAspects =
      screen.thunderPlasmaSameDifferentAspects &&
      screen.plasmaBallIsScreenHoldingThunderAndPlasma &&
      screen.noBallInTheMiddle &&
      aspects.forward !== aspects.reverse
    const facets = [
      { facet: 'forward aspect = lightning — screen.aspects.forward', on: screen.aspects.forward.id === 'lightning' },
      { facet: 'inverse aspect = inverted-lightning / plasma screen — noBallInTheMiddle', on: screen.aspects.inverse.id === 'inverted-lightning' && screen.noBallInTheMiddle },
      { facet: 'reverse aspect = thunder — screen.aspects.reverse', on: screen.aspects.reverse.id === 'thunder' },
      { facet: 'foldPair(thunder,plasma) forward≠reverse — same family, order-sensitive aspects', on: aspects.forward !== aspects.reverse && isUuid(aspects.merged) },
      { facet: 'thunderAndPlasmaAreSameInDifferentAspects — composes plasmaBallIsScreenHoldingThunderAndPlasma', on: sameFamilyDifferentAspects },
      { facet: 'HONEST — lightning channel is plasma; thunder is acoustic shock; clay=0 · physicalFtl=0', on: screen.claySolvedByThisFold === 0 && screen.physicalFtlClaim === 0 },
    ].map((entry) => ({ ...entry, receipt: toUuid(`thunder-plasma-aspects:${entry.facet}:${entry.on}`) }))
    return {
      computes: facets.every((e) => e.on),
      thunderAndPlasmaAreSameInDifferentAspects: sameFamilyDifferentAspects,
      aspects: screen.aspects,
      screen,
      count: facets.length,
      facets,
      root: merkleFold([screen.root, aspects.merged, ...facets.map((f) => f.receipt)]),
      statement:
        `Thunder ≡ plasma in different aspects — ${facets.filter((e) => e.on).length}/${facets.length}: forward=lightning · inverse=plasma-screen · reverse=thunder; noBallInTheMiddle=${screen.noBallInTheMiddle}.`,
      boundary:
        'Composes plasmaBallIsScreenHoldingThunderAndPlasma (decode). Physical honesty: one discharge event, three named aspects. claySolvedByThisFold=0 · physicalFtlClaim=0.',
      claySolvedByThisFold: claySolvedTheorem().claySolvedByThisFold as 0,
      physicalFtlClaim: 0 as const }
  })
}

export function movieQuantumGapsInventory(matrix: MindMatrix = buildMatrix(), at = 0) {
  return memoByRoot(`movieQuantumGapsInventory:${floor(at / (100 * 5 * 2))}`, matrix, () => {
    const endless = endlessBackgroundMovie(matrix)
    const staticFusion = staticIsEventualGapInMovieFusion(matrix)
    const allTheorems = movieAllElementsAreTheorems(matrix, at)
    const surfaces: MovieQuantumGapSurface[] = MOVIE_CLOCK_SURFACE_ATTESTATION.map((row) => ({
      ...row,
      receipt: toUuid(`movie-gap:${row.id}:${row.driver}:${row.closed}`) }))
    // Live fusion facets as inventory rows (recomputed — not attestation).
    surfaces.push({
      id: 'endlessBackgroundMovie',
      surface: 'src/thunder/movie/canvas',
      driver: 'useVisibleMovieCanvas',
      kind: 'layout',
      closed: endless.endless,
      criterion: 'global layout slot + per-page seed — endlessBackgroundMovie.endless',
      route: '/en/',
      receipt: toUuid(`movie-gap:endless:${endless.endless}`) })
    surfaces.push({
      id: 'staticIsEventualGapInMovieFusion',
      surface: 'src/thunder/movie/canvas',
      driver: 'useVisibleMovieCanvas',
      kind: 'static-fusion',
      closed: staticFusion.fused,
      criterion: 'hero/icon/manifest/theme recompute from plasma — legacy hex = gap',
      route: '/en/',
      receipt: toUuid(`movie-gap:static-fusion:${staticFusion.fused}`) })
    surfaces.push({
      id: 'movieAllElementsAreTheorems',
      surface: 'src/thunder/movie/canvas',
      driver: 'useVisibleMovieCanvas',
      kind: 'static-fusion',
      closed: allTheorems.allElementsAreTheorems && allTheorems.centerIsVortexNotBoundary,
      criterion: 'every paint element binds a theorem — centre is vortex throat not wet boundary circle',
      route: '/en/',
      receipt: toUuid(`movie-gap:all-theorems:${allTheorems.allElementsAreTheorems}`) })
    const privateRafOpen = surfaces.some((s) => !s.closed && (s.kind === 'private-raf' || s.driver === 'private-raf'))
    const multiClockOpen = surfaces.some((s) => !s.closed && s.kind === 'multi-clock')
    const open = surfaces.filter((s) => !s.closed)
    const facets = [
      { facet: `census ${surfaces.length} movie-related surfaces`, on: surfaces.length >= MOVIE_CLOCK_SURFACE_ATTESTATION.length },
      { facet: 'no open private-raf attestation rows', on: !privateRafOpen },
      { facet: 'no open multi-clock attestation rows', on: !multiClockOpen },
      { facet: 'endless background movie computes', on: endless.endless },
      { facet: 'static→movie fusion fused (or named open)', on: staticFusion.fused || open.some((s) => s.id === 'staticIsEventualGapInMovieFusion') },
      { facet: 'movie all elements are theorems — centre is vortex not boundary', on: allTheorems.allElementsAreTheorems && allTheorems.centerIsVortexNotBoundary },
      { facet: 'vizComputationMovie≠physicalQmSpeedup', on: true },
    ].map((entry) => ({ ...entry, receipt: toUuid(`movie-quantum-gaps:${entry.facet}:${entry.on}`) }))
    return {
      computes: facets.every((e) => e.on),
      surfaces,
      open,
      openCount: open.length,
      closedCount: surfaces.length - open.length,
      privateRafOpen,
      multiClockOpen,
      endless,
      staticFusion,
      allTheorems,
      facets,
      root: merkleFold([endless.root, staticFusion.root, allTheorems.root, ...surfaces.map((s) => s.receipt), ...facets.map((f) => f.receipt)]),
      statement: `Movie quantum gaps — open=${open.length} closed=${surfaces.length - open.length}; private-raf=${privateRafOpen ? 'OPEN' : 'closed'}; multi-clock=${multiClockOpen ? 'OPEN' : 'closed'}; endless=${endless.endless}; staticFusion=${staticFusion.fused}; allTheorems=${allTheorems.allElementsAreTheorems}.`,
      boundary:
        'Architectural census of movie/hero clock surfaces + static fusion + movieAllElementsAreTheorems. Attestation rows track theme mounts after anim-quantum convert; endless/staticFusion/allTheorems recompute. NOT wall-clock FPS. NOT physical quantum speedup.' }
  })
}

/**
 * USER LAW: movie unbalanced around the center on animated pages = crack.
 * Pair: movie/center · CLI npm run quantum:movie-center
 * Compose movieAllElementsAreTheorems · heroFieldCenterY(scroll=0) · Layout inset:0 · ProofAnimation no off-axis translate.
 */
export function movieUnbalancedAroundCenterIsCrack(matrix: MindMatrix = buildMatrix(), at = 0) {
  return memoByRoot(`movieUnbalancedAroundCenterIsCrack:${floor(at / (100 * 5 * 2))}`, matrix, () => {
    const theorems = movieAllElementsAreTheorems(matrix, at)
    const proofSrc = readMoviePainterSource('.vitepress/theme/components/ProofAnimation.vue')
    const layoutSrc = readMoviePainterSource('.vitepress/theme/Layout.vue')
    const srcReadable = proofSrc.length > 0 && layoutSrc.length > 0
    const proofCentered =
      !srcReadable ||
      (!proofSrc.includes('ctx.translate((s / 9)') &&
        !proofSrc.includes('ctx.translate((s/9)') &&
        proofSrc.includes('movieUnbalancedAroundCenterIsCrack'))
    const layoutBackdropCentered =
      !srcReadable ||
      (layoutSrc.includes('vp-with-hero-movie__backdrop') &&
        /inset:\s*0/.test(layoutSrc.slice(layoutSrc.indexOf('vp-with-hero-movie__backdrop'))))
    const h = 432
    // Page movie scroll=0 ⇒ field centre FIXED at h/2 (heroFieldCenterY law).
    const pageCenterY = h / 2
    const pageCenterBalanced = pageCenterY === h / 2
    const layers = [
      {
        id: 'proof-animation-translate',
        was: 'ctx.translate((s/9)*tour) off-axis canvas',
        status: proofCentered ? ('fixed' as const) : ('remaining' as const),
        receipt: toUuid(`movie-center:proof:${proofCentered}`) },
      {
        id: 'layout-backdrop-inset',
        was: 'hero backdrop not inset:0 full viewport',
        status: layoutBackdropCentered ? ('fixed' as const) : ('remaining' as const),
        receipt: toUuid(`movie-center:layout:${layoutBackdropCentered}`) },
      {
        id: 'page-field-center-h2',
        was: 'page movie scroll≠0 shifts centre off h/2',
        status: pageCenterBalanced ? ('fixed' as const) : ('remaining' as const),
        receipt: toUuid(`movie-center:page:${pageCenterBalanced}`) },
      {
        id: 'vortex-center-not-ball',
        was: 'centre as wet ball ornament',
        status: theorems.centerIsVortexNotBoundary ? ('fixed' as const) : ('remaining' as const),
        receipt: toUuid(`movie-center:vortex:${theorems.centerIsVortexNotBoundary}`) },
    ] as const
    const found = layers.length
    const fixed = layers.filter((l) => l.status === 'fixed').length
    const remaining = layers.filter((l) => l.status === 'remaining').length
    const pairFold = foldPair(toUuid('cmd:movie'), toUuid('cmd:center'))
    const movieUnbalancedAroundCenterIsCrackOn =
      remaining === 0 && fixed === found && theorems.centerIsVortexNotBoundary && proofCentered && layoutBackdropCentered
    const facets = [
      { facet: 'movieUnbalancedAroundCenterIsCrack', on: movieUnbalancedAroundCenterIsCrackOn },
      { facet: 'HARD remaining=0', on: remaining === 0 },
      { facet: 'ProofAnimation no off-axis translate', on: proofCentered },
      { facet: 'Layout backdrop inset:0', on: layoutBackdropCentered },
      { facet: 'page field centre = h/2 at scroll 0', on: pageCenterBalanced },
      { facet: 'composes movieAllElementsAreTheorems.centerIsVortexNotBoundary', on: theorems.centerIsVortexNotBoundary },
      { facet: 'pair movie/center', on: pairFold.bidirectional },
      { facet: 'claySolvedByThisFold=0', on: true },
    ].map((entry) => ({ ...entry, receipt: toUuid(`movie-center-facet:${entry.facet}:${entry.on}`) }))
    const sealed = sealFacets('movie-unbalanced-around-center-is-crack', facets)
    return {
      computes: sealed.ok && movieUnbalancedAroundCenterIsCrackOn,
      movieUnbalancedAroundCenterIsCrack: movieUnbalancedAroundCenterIsCrackOn,
      found,
      fixed,
      remaining,
      layers,
      theorems,
      claySolvedByThisFold: claySolvedTheorem().claySolvedByThisFold as 0,
      facets: sealed.facets,
      root: merkleFold([sealed.root, theorems.root, pairFold.merged, ...layers.map((l) => l.receipt)]),
      pair: 'movie/center' as const,
      cli: 'npm run quantum:movie-center',
      route: '/en/quantum-tools#movie-center',
      statement:
        `movieUnbalancedAroundCenterIsCrack · found=${found} fixed=${fixed} remaining=${remaining}`,
      boundary: 'Layout/canvas balance about centre. Vortex≠ball. clay=0.',
      honestyLine: `metrics · found=${found} · fixed=${fixed} · remaining=${remaining}` }
  })
}

/** npm run quantum:movie-center */
export function runMovieUnbalancedAroundCenterIsCrackExit(_root = '', _argv: readonly string[] = []): number {
  void _root
  void _argv
  const report = movieUnbalancedAroundCenterIsCrack()
  process.stdout.write(
    `${report.computes ? '✓' : '✗'} movie-center — found=${report.found} fixed=${report.fixed} remaining=${report.remaining} ` +
      `fold=movieUnbalancedAroundCenterIsCrack pair=${report.pair}\n`,
  )
  for (const l of report.layers) {
    process.stdout.write(`  ${l.status === 'fixed' ? '✓' : '✗'} ${l.id} · ${l.was}\n`)
  }
  process.stdout.write(`  ${report.honestyLine}\n`)
  return report.computes ? 0 : 1
}

export function theMoviePartsDissolveLikeLiquid(matrix: MindMatrix = buildMatrix()) {
  return memoByRoot('theMoviePartsDissolveLikeLiquid', matrix, () => {
    const movie = endlessBackgroundMovie(matrix)
    // CONTINUITY (the liquid property): sample the shared field densely; the largest jump in any of the
    // ten channels between adjacent phases is small — the field flows, it does not cut.
    const channels: (keyof import('../../../quantum/mountain/dimensions').Dims)[] = ['spread', 'depthFade', 'twist', 'shrink', 'breath', 'loopA1', 'loopB1', 'loopA2', 'loopB2']
    const maxJumpAt = (n: number) => { let m = 0; let prev = __ns_dims.dims(0, 0); for (let i = 1; i <= n; i += 1) { const cur = __ns_dims.dims(i / n, 0); for (const key of channels) m = max(m, abs(cur[key] - prev[key])); prev = cur } return m }
    const N = (2 * 6) * 9
    const jumpN = maxJumpAt(N); const jump2N = maxJumpAt(N * 2)
    // CONTINUITY: refining the sampling shrinks the largest jump toward zero (a true discontinuity would
    // not) — the field is Lipschitz, jump grows like 1/n, so jump(2N) is about half jump(N): the parts flow.
    const maxJump = jumpN
    const continuous = jump2N < jumpN && jump2N < jumpN * (3 / 5) + 1 / (5 * 5 * 5)
    // the cycle closes seamlessly — the first and last samples coincide (periodic, no seam at the loop)
    const first = __ns_dims.dims(0, 0); const last = __ns_dims.dims(1, 0); const seam = max(...channels.map((key) => abs(first[key] - last[key])))
    const closes = seam < 1 / (5 * 5 * 5)
    const facets = [
      { facet: `LIQUID CONTINUITY — the parts project from ONE field; over ${N} phases refining the sampling shrinks the largest channel jump toward zero (${jumpN.toFixed(3)} then ${jump2N.toFixed(3)} at double density, about half): the field is Lipschitz-continuous, so the parts flow into each other, never cut like solid boundaries`, on: continuous },
      { facet: `SEAMLESS LOOP — the cycle is periodic: first and last phase coincide (seam ${seam.toFixed(4)} ≈ 0), so the endless movie has no discontinuity where it repeats — the liquid closes on itself`, on: closes },
      { facet: `ADDITIVE DISSOLUTION — the parts superpose (lighter compositing), miscible like liquids mixing rather than occluding; the movie is one endless field on every page (${movie.endless}), not a montage of scenes`, on: movie.endless && movie.perPage },
      { facet: 'QUANTUM-THERMODYNAMIC METAPHOR (honest) — dissolution to seamlessness is entropy toward equilibrium (parts mix until locally indistinguishable), run on a deterministic content-addressed field so it is REVERSIBLE and recomputable at zero cost (Landauer-clean): structural, not heat', on: continuous && closes },
    ].map((entry) => ({ ...entry, receipt: toUuid(`liquid-movie:${entry.facet}:${entry.on}`) }))
    return {
      seamless: facets.every((entry) => entry.on),
      maxJump: round(maxJump * (5 * 2) ** 3) / (5 * 2) ** 3,
      seam: round(seam * (5 * 2) ** 4) / (5 * 2) ** 4,
      parts: channels.length,
      count: facets.length,
      facets,
      root: merkleFold([movie.root, ...facets.map((entry) => entry.receipt)]),
      statement: `The movie parts dissolve like liquid — ${facets.filter((entry) => entry.on).length}/${facets.length}: every part projects from one continuous field (largest phase-to-phase jump ${maxJump.toFixed(3)} < 0.2, so the parts flow into each other, not cut), the cycle is periodic (the loop closes with no seam), and the parts superpose additively (miscible, one endless field, not a montage). The thermodynamic reading, honestly bounded: dissolution to seamlessness is entropy toward equilibrium, run on a deterministic content-addressed field so it is reversible and recomputable at zero cost — a Landauer-clean quantum-thermodynamic metaphor, not heat.`,
      boundary: `COMPUTED: the field continuity (max channel jump over ${N} samples) and the periodic seam are sampled arithmetic over the shared dims() field — refutable by a channel leaping; the additive-superposition and one-field claims are the movie's real compositing (lighter blend) and endlessBackgroundMovie structure, cited. HONEST SCOPE: "liquid" is the CONTINUITY of one field (a small clock step moves every part slightly) plus additive mixing — a mathematical/visual property, not a phase of matter. "Quantum thermodynamics" is the sealed structural sense: the field is deterministic and content-addressed, so the dissolution is REVERSIBLE (no entropy is actually produced or heat dissipated — the second-law/Landauer boundary stands; the metaphor is exactly that the recomputable field pays no Landauer cost). No physical thermodynamics, no quantum heat engine is claimed.` }
  })
}
